import {
  abstract,
  acala,
  adi,
  alephZero,
  ancient8,
  apeChain,
  arbitrum,
  arbitrumNova,
  astar,
  aurora,
  avalanche,
  b3,
  base,
  berachain,
  bitlayer,
  blast,
  bob,
  boba,
  botanix,
  bounceBit,
  bsc,
  bsquared,
  canto,
  celo,
  chiliz,
  citrea,
  confluxESpace,
  coreDao,
  corn,
  cronos,
  cronoszkEVM,
  cyber,
  degen,
  dogechain,
  eden,
  electroneum,
  eni,
  evmos,
  fantom,
  filecoin,
  flare,
  flowMainnet,
  fluent,
  forma,
  fraxtal,
  funkiMainnet,
  fuse,
  gnosis,
  gravity,
  guruNetwork,
  harmonyOne,
  hashkey,
  hemi,
  hyperEvm,
  igra,
  immutableZkEvm,
  inEVM,
  ink,
  kaia,
  katana,
  kava,
  kii,
  kinto,
  kroma,
  krown,
  lens,
  lightlinkPhoenix,
  linea,
  lisk,
  lukso,
  lumiaMainnet,
  mainnet,
  manta,
  mantle,
  mantraEVM,
  matchain,
  megaeth,
  merlin,
  metalL2,
  metis,
  mint,
  mode,
  monad,
  moonbeam,
  moonriver,
  morph,
  nibiru,
  opBNB,
  optimism,
  orderly,
  peaq,
  plasma,
  plumeMainnet,
  polygon,
  polygonZkEvm,
  polynomial,
  pulsechain,
  real,
  redstone,
  robinhood,
  ronin,
  rootstock,
  saakuru,
  scroll,
  sei,
  shape,
  shibarium,
  snax,
  somnia,
  soneium,
  sonic,
  sophon,
  sova,
  stable,
  story,
  subtensorEvm,
  superposition,
  superseed,
  swellchain,
  syscoin,
  tac,
  taiko,
  telos,
  tempo,
  tenet,
  treasure,
  tron,
  unichain,
  vana,
  viction,
  worldchain,
  xLayer,
  xai,
  xpla,
  xrplevm,
  zeroGMainnet,
  zeroNetwork,
  zetachain,
  zircuit,
  zkLinkNova,
  zkSync,
  zora,
} from "viem/chains";
import type { Chain } from "viem";
import { SVM_CHAINS, resolveSvmChain } from "./svmChains";
import { COSMOS_CHAINS, resolveCosmosChain } from "./cosmosChains";
import { OTHER_CHAINS, resolveOtherChain } from "./otherChains";

/**
 * Every EVM chain the bot knows how to talk to.
 * `key` is the identifier used everywhere in commands, the DB, and config
 * (env var names, aliases, etc). Add a new chain by adding an entry here
 * plus its RPC env var default in env.ts, and (optionally) known bridge
 * addresses in protocols/addresses/*.
 */
export interface ChainDef {
  key: string;
  label: string;
  viemChain: Chain;
  rpcEnvVar: string;
  /**
   * Public endpoints tried in order when no custom RPC is configured.
   * More than one because a single free endpoint routinely refuses
   * requests coming from a datacenter IP, which is exactly where this bot
   * runs; viem's fallback transport moves on to the next one.
   */
  defaultRpcUrls: string[];
  explorerTxUrl: (hash: string) => string;
  explorerAddressUrl: (address: string) => string;
  /** Alternate names users may type after /info or /track. */
  aliases: string[];
  /** How CoinMarketCap spells this network in its platform field. */
  cmcPlatformNames?: string[];
  /**
   * Reads to run at once against this chain's node. The default suits a
   * normal endpoint; a chain whose public node rate-limits harder needs
   * less, and being throttled costs a whole row - which reads as "no
   * liquidity here" rather than as a node saying no.
   */
  maxConcurrentReads?: number;
}

/**
 * Chains removed on 2026-09-10, and why: every hostname they were listed
 * under - across chainlist, ethereum-lists/chains and Hyperlane's own
 * registry - had stopped resolving. Not refusing, not rate-limiting: gone
 * from DNS, with nothing left to point a private RPC at.
 *
 *   Arthera, Astar zkEVM, Flame, Fluence, Form Network, Ham, Nautilus,
 *   Rivalz, Sanko, Taraxa
 *
 * The bar was deliberately this narrow. A chain answering 403 or 429 is
 * alive and refusing a datacenter IP, which a key fixes, so those stayed.
 * And a hostname that has died is not the same as a chain that has: Astar
 * zkEVM lost two hosts in two registries before the third was checked, and
 * Zero Network looked just as dead until Hyperlane turned out to have two
 * that answer. Both were kept for that reason; these ten survived all three.
 *
 * Re-checkable, not a judgement to take on faith: `npm run check:dead`
 * runs the same sweep. If one of these ever resolves again, it belongs back
 * here.
 */
export const CHAINS: ChainDef[] = [
  {
    key: "ethereum",
    label: "Ethereum",
    viemChain: mainnet,
    rpcEnvVar: "ETHEREUM_RPC_URL",
    defaultRpcUrls: [
      "https://ethereum-rpc.publicnode.com",
      "https://eth.llamarpc.com",
      "https://rpc.ankr.com/eth",
      "https://cloudflare-eth.com",
    ],
    explorerTxUrl: (h) => `https://etherscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://etherscan.io/address/${a}`,
    aliases: ["eth", "mainnet", "ethereum"],
    cmcPlatformNames: ["Ethereum", "ERC20"],
  },
  {
    key: "arbitrum",
    label: "Arbitrum One",
    viemChain: arbitrum,
    rpcEnvVar: "ARBITRUM_RPC_URL",
    defaultRpcUrls: [
      "https://arb1.arbitrum.io/rpc",
      "https://arbitrum-one-rpc.publicnode.com",
      "https://rpc.ankr.com/arbitrum",
    ],
    explorerTxUrl: (h) => `https://arbiscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://arbiscan.io/address/${a}`,
    aliases: ["arb", "arbitrum", "arbitrum-one"],
    cmcPlatformNames: ["Arbitrum", "Arbitrum One"],
  },
  {
    key: "optimism",
    label: "Optimism",
    viemChain: optimism,
    rpcEnvVar: "OPTIMISM_RPC_URL",
    defaultRpcUrls: [
      "https://mainnet.optimism.io",
      "https://optimism-rpc.publicnode.com",
      "https://rpc.ankr.com/optimism",
    ],
    explorerTxUrl: (h) => `https://optimistic.etherscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://optimistic.etherscan.io/address/${a}`,
    aliases: ["op", "optimism"],
    cmcPlatformNames: ["Optimism", "OP Mainnet"],
  },
  {
    key: "base",
    label: "Base",
    viemChain: base,
    rpcEnvVar: "BASE_RPC_URL",
    defaultRpcUrls: [
      "https://mainnet.base.org",
      "https://base-rpc.publicnode.com",
    ],
    explorerTxUrl: (h) => `https://basescan.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://basescan.org/address/${a}`,
    aliases: ["base"],
    cmcPlatformNames: ["Base"],
  },
  {
    key: "polygon",
    label: "Polygon",
    viemChain: polygon,
    rpcEnvVar: "POLYGON_RPC_URL",
    defaultRpcUrls: [
      "https://polygon-rpc.com",
      "https://polygon-bor-rpc.publicnode.com",
      "https://rpc.ankr.com/polygon",
    ],
    explorerTxUrl: (h) => `https://polygonscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://polygonscan.com/address/${a}`,
    aliases: ["polygon", "matic", "pol"],
    cmcPlatformNames: ["Polygon", "Polygon PoS", "Polygon Ecosystem"],
  },
  {
    key: "bsc",
    label: "BNB Chain",
    viemChain: bsc,
    rpcEnvVar: "BSC_RPC_URL",
    defaultRpcUrls: [
      "https://bsc-dataseed.binance.org",
      "https://bsc-rpc.publicnode.com",
      "https://rpc.ankr.com/bsc",
    ],
    explorerTxUrl: (h) => `https://bscscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://bscscan.com/address/${a}`,
    aliases: ["bsc", "bnb", "binance"],
    cmcPlatformNames: ["BNB Smart Chain (BEP20)", "BNB Smart Chain", "Binance Smart Chain", "BNB"],
  },
  {
    key: "avalanche",
    label: "Avalanche C-Chain",
    viemChain: avalanche,
    rpcEnvVar: "AVALANCHE_RPC_URL",
    defaultRpcUrls: [
      "https://api.avax.network/ext/bc/C/rpc",
      "https://avalanche-c-chain-rpc.publicnode.com",
    ],
    explorerTxUrl: (h) => `https://snowtrace.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://snowtrace.io/address/${a}`,
    aliases: ["avax", "avalanche"],
    cmcPlatformNames: ["Avalanche C-Chain", "Avalanche"],
  },
  // --- added later; RPC and explorer come from viem's own chain metadata
  // rather than being retyped here, and the `key` must match the chain name
  // Hyperlane's warp-route registry uses, since that is what matches routes.
  {
    key: "unichain",
    label: "Unichain",
    viemChain: unichain,
    rpcEnvVar: "UNICHAIN_RPC_URL",
    defaultRpcUrls: ["https://mainnet.unichain.org"],
    explorerTxUrl: (h) => `https://uniscan.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://uniscan.xyz/address/${a}`,
    aliases: ["unichain", "uni"],
    cmcPlatformNames: ["Unichain"],
  },
  {
    key: "ink",
    label: "Ink",
    viemChain: ink,
    rpcEnvVar: "INK_RPC_URL",
    defaultRpcUrls: ["https://rpc-gel.inkonchain.com", "https://rpc-qnd.inkonchain.com"],
    explorerTxUrl: (h) => `https://explorer.inkonchain.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.inkonchain.com/address/${a}`,
    aliases: ["ink"],
    cmcPlatformNames: ["Ink"],
  },
  {
    key: "linea",
    label: "Linea",
    viemChain: linea,
    rpcEnvVar: "LINEA_RPC_URL",
    defaultRpcUrls: ["https://rpc.linea.build"],
    explorerTxUrl: (h) => `https://lineascan.build/tx/${h}`,
    explorerAddressUrl: (a) => `https://lineascan.build/address/${a}`,
    aliases: ["linea"],
    cmcPlatformNames: ["Linea"],
  },
  {
    key: "worldchain",
    label: "World Chain",
    viemChain: worldchain,
    rpcEnvVar: "WORLDCHAIN_RPC_URL",
    defaultRpcUrls: ["https://worldchain-mainnet.g.alchemy.com/public"],
    explorerTxUrl: (h) => `https://worldscan.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://worldscan.org/address/${a}`,
    aliases: ["worldchain", "world"],
    cmcPlatformNames: ["World Chain", "Worldchain"],
  },
  {
    key: "mode",
    label: "Mode",
    viemChain: mode,
    rpcEnvVar: "MODE_RPC_URL",
    defaultRpcUrls: ["https://mainnet.mode.network"],
    explorerTxUrl: (h) => `https://modescan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://modescan.io/address/${a}`,
    aliases: ["mode"],
    cmcPlatformNames: ["Mode"],
  },
  {
    key: "berachain",
    label: "Berachain",
    viemChain: berachain,
    rpcEnvVar: "BERACHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.berachain.com"],
    explorerTxUrl: (h) => `https://berascan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://berascan.com/address/${a}`,
    aliases: ["berachain", "bera"],
    cmcPlatformNames: ["Berachain"],
  },
  {
    key: "blast",
    label: "Blast",
    viemChain: blast,
    rpcEnvVar: "BLAST_RPC_URL",
    defaultRpcUrls: ["https://rpc.blast.io"],
    explorerTxUrl: (h) => `https://blastscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://blastscan.io/address/${a}`,
    aliases: ["blast"],
    cmcPlatformNames: ["Blast"],
  },
  {
    key: "celo",
    label: "Celo",
    viemChain: celo,
    rpcEnvVar: "CELO_RPC_URL",
    defaultRpcUrls: ["https://forno.celo.org"],
    explorerTxUrl: (h) => `https://celoscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://celoscan.io/address/${a}`,
    aliases: ["celo"],
    cmcPlatformNames: ["Celo"],
  },
  {
    key: "katana",
    label: "Katana",
    viemChain: katana,
    rpcEnvVar: "KATANA_RPC_URL",
    defaultRpcUrls: ["https://rpc.katana.network"],
    explorerTxUrl: (h) => `https://katanascan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://katanascan.com/address/${a}`,
    aliases: ["katana"],
  },
  {
    key: "hyperevm",
    label: "HyperEVM",
    viemChain: hyperEvm,
    rpcEnvVar: "HYPEREVM_RPC_URL",
    defaultRpcUrls: ["https://rpc.hyperliquid.xyz/evm"],
    explorerTxUrl: (h) => `https://hyperevmscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://hyperevmscan.io/address/${a}`,
    aliases: ["hyperevm", "hyperliquid", "hype"],
    cmcPlatformNames: ["HyperEVM", "Hyperliquid"],
  },
  {
    key: "monad",
    label: "Monad",
    viemChain: monad,
    rpcEnvVar: "MONAD_RPC_URL",
    defaultRpcUrls: ["https://rpc.monad.xyz", "https://rpc1.monad.xyz"],
    explorerTxUrl: (h) => `https://monadscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://monadscan.com/address/${a}`,
    aliases: ["monad"],
    cmcPlatformNames: ["Monad"],
  },
  {
    key: "plasma",
    label: "Plasma",
    viemChain: plasma,
    rpcEnvVar: "PLASMA_RPC_URL",
    defaultRpcUrls: ["https://rpc.plasma.to"],
    explorerTxUrl: (h) => `https://plasmascan.to/tx/${h}`,
    explorerAddressUrl: (a) => `https://plasmascan.to/address/${a}`,
    aliases: ["plasma"],
  },
  {
    key: "sei",
    label: "Sei Network",
    viemChain: sei,
    rpcEnvVar: "SEI_RPC_URL",
    defaultRpcUrls: ["https://evm-rpc.sei-apis.com/"],
    explorerTxUrl: (h) => `https://seiscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://seiscan.io/address/${a}`,
    aliases: ["sei"],
    cmcPlatformNames: ["Sei v2", "Sei"],
  },
  {
    key: "swell",
    label: "Swellchain",
    viemChain: swellchain,
    rpcEnvVar: "SWELL_RPC_URL",
    defaultRpcUrls: [
      "https://swell-mainnet.alt.technology",
      "https://swell.drpc.org",
      "https://rpc.ankr.com/swell",
    ],
    explorerTxUrl: (h) => `https://explorer.swellnetwork.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.swellnetwork.io/address/${a}`,
    aliases: ["swell"],
  },
  {
    key: "superseed",
    label: "Superseed",
    viemChain: superseed,
    rpcEnvVar: "SUPERSEED_RPC_URL",
    defaultRpcUrls: ["https://mainnet.superseed.xyz"],
    explorerTxUrl: (h) => `https://explorer.superseed.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.superseed.xyz/address/${a}`,
    aliases: ["superseed"],
  },
  {
    key: "fraxtal",
    label: "Fraxtal",
    viemChain: fraxtal,
    rpcEnvVar: "FRAXTAL_RPC_URL",
    defaultRpcUrls: ["https://rpc.frax.com"],
    explorerTxUrl: (h) => `https://fraxscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://fraxscan.com/address/${a}`,
    aliases: ["fraxtal"],
    cmcPlatformNames: ["Fraxtal"],
  },
  {
    key: "zircuit",
    label: "Zircuit Mainnet",
    viemChain: zircuit,
    rpcEnvVar: "ZIRCUIT_RPC_URL",
    defaultRpcUrls: ["https://mainnet.zircuit.com"],
    explorerTxUrl: (h) => `https://explorer.zircuit.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zircuit.com/address/${a}`,
    aliases: ["zircuit"],
  },
  {
    key: "soneium",
    label: "Soneium Mainnet",
    viemChain: soneium,
    rpcEnvVar: "SONEIUM_RPC_URL",
    defaultRpcUrls: ["https://rpc.soneium.org"],
    explorerTxUrl: (h) => `https://soneium.blockscout.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://soneium.blockscout.com/address/${a}`,
    aliases: ["soneium"],
    cmcPlatformNames: ["Soneium"],
  },
  {
    key: "mantle",
    label: "Mantle",
    viemChain: mantle,
    rpcEnvVar: "MANTLE_RPC_URL",
    defaultRpcUrls: ["https://rpc.mantle.xyz"],
    explorerTxUrl: (h) => `https://mantlescan.xyz//tx/${h}`,
    explorerAddressUrl: (a) => `https://mantlescan.xyz//address/${a}`,
    aliases: ["mantle"],
    cmcPlatformNames: ["Mantle"],
  },
  {
    key: "taiko",
    label: "Taiko Mainnet",
    viemChain: taiko,
    rpcEnvVar: "TAIKO_RPC_URL",
    defaultRpcUrls: ["https://rpc.mainnet.taiko.xyz"],
    explorerTxUrl: (h) => `https://taikoscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://taikoscan.io/address/${a}`,
    aliases: ["taiko"],
    cmcPlatformNames: ["Taiko"],
  },
  {
    key: "xlayer",
    label: "X Layer Mainnet",
    viemChain: xLayer,
    rpcEnvVar: "XLAYER_RPC_URL",
    defaultRpcUrls: ["https://xlayerrpc.okx.com"],
    explorerTxUrl: (h) => `https://www.oklink.com/xlayer/tx/${h}`,
    explorerAddressUrl: (a) => `https://www.oklink.com/xlayer/address/${a}`,
    aliases: ["xlayer", "okx"],
  },
  {
    key: "plume",
    label: "Plume",
    viemChain: plumeMainnet,
    rpcEnvVar: "PLUME_RPC_URL",
    defaultRpcUrls: ["https://rpc.plume.org"],
    explorerTxUrl: (h) => `https://explorer.plume.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.plume.org/address/${a}`,
    aliases: ["plume"],
    cmcPlatformNames: ["Plume"],
  },
  {
    key: "sonic",
    label: "Sonic",
    viemChain: sonic,
    rpcEnvVar: "SONIC_RPC_URL",
    defaultRpcUrls: ["https://rpc.soniclabs.com"],
    explorerTxUrl: (h) => `https://sonicscan.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://sonicscan.org/address/${a}`,
    aliases: ["sonic"],
    cmcPlatformNames: ["Sonic", "Fantom"],
  },
  {
    key: "scroll",
    label: "Scroll",
    viemChain: scroll,
    rpcEnvVar: "SCROLL_RPC_URL",
    defaultRpcUrls: ["https://rpc.scroll.io"],
    explorerTxUrl: (h) => `https://scrollscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://scrollscan.com/address/${a}`,
    aliases: ["scroll"],
    cmcPlatformNames: ["Scroll"],
  },
  {
    key: "bob",
    label: "BOB",
    viemChain: bob,
    rpcEnvVar: "BOB_RPC_URL",
    defaultRpcUrls: ["https://rpc.gobob.xyz"],
    explorerTxUrl: (h) => `https://explorer.gobob.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.gobob.xyz/address/${a}`,
    aliases: ["bob", "buildonbitcoin"],
  },
  {
    key: "lisk",
    label: "Lisk",
    viemChain: lisk,
    rpcEnvVar: "LISK_RPC_URL",
    defaultRpcUrls: ["https://rpc.api.lisk.com"],
    explorerTxUrl: (h) => `https://blockscout.lisk.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://blockscout.lisk.com/address/${a}`,
    aliases: ["lisk"],
    cmcPlatformNames: ["Lisk"],
  },
  {
    key: "metal",
    label: "Metal L2",
    viemChain: metalL2,
    rpcEnvVar: "METAL_RPC_URL",
    defaultRpcUrls: ["https://rpc.metall2.com"],
    explorerTxUrl: (h) => `https://explorer.metall2.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.metall2.com/address/${a}`,
    aliases: ["metal"],
  },
  {
    key: "gnosis",
    label: "Gnosis",
    viemChain: gnosis,
    rpcEnvVar: "GNOSIS_RPC_URL",
    defaultRpcUrls: ["https://rpc.gnosischain.com"],
    explorerTxUrl: (h) => `https://gnosisscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://gnosisscan.io/address/${a}`,
    aliases: ["gnosis", "xdai"],
    cmcPlatformNames: ["Gnosis Chain", "Gnosis", "xDai"],
  },
  {
    key: "zerogravity",
    label: "0G Mainnet",
    viemChain: zeroGMainnet,
    rpcEnvVar: "ZEROGRAVITY_RPC_URL",
    defaultRpcUrls: ["https://evmrpc.0g.ai"],
    explorerTxUrl: (h) => `https://chainscan.0g.ai/tx/${h}`,
    explorerAddressUrl: (a) => `https://chainscan.0g.ai/address/${a}`,
    aliases: ["zerogravity", "0g"],
  },
  {
    key: "zksync",
    label: "ZKsync Era",
    viemChain: zkSync,
    rpcEnvVar: "ZKSYNC_RPC_URL",
    defaultRpcUrls: ["https://mainnet.era.zksync.io"],
    explorerTxUrl: (h) => `https://explorer.zksync.io//tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zksync.io//address/${a}`,
    aliases: ["zksync", "zksyncera", "era"],
    cmcPlatformNames: ["zkSync Era", "zkSync"],
  },
  {
    key: "cronoszkevm",
    label: "Cronos zkEVM Mainnet",
    viemChain: cronoszkEVM,
    rpcEnvVar: "CRONOSZKEVM_RPC_URL",
    defaultRpcUrls: ["https://mainnet.zkevm.cronos.org"],
    explorerTxUrl: (h) => `https://explorer.zkevm.cronos.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zkevm.cronos.org/address/${a}`,
    aliases: ["cronoszkevm"],
  },
  {
    key: "moonbeam",
    label: "Moonbeam",
    viemChain: moonbeam,
    rpcEnvVar: "MOONBEAM_RPC_URL",
    defaultRpcUrls: [
      "https://rpc.api.moonbeam.network",
      "https://moonbeam-rpc.publicnode.com",
      "https://moonbeam.public.blastapi.io",
      "https://moonbeam.drpc.org",
    ],
    explorerTxUrl: (h) => `https://moonscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://moonscan.io/address/${a}`,
    aliases: ["moonbeam"],
    cmcPlatformNames: ["Moonbeam"],
  },
  {
    key: "aurora",
    label: "Aurora",
    viemChain: aurora,
    rpcEnvVar: "AURORA_RPC_URL",
    defaultRpcUrls: ["https://mainnet.aurora.dev"],
    explorerTxUrl: (h) => `https://aurorascan.dev/tx/${h}`,
    explorerAddressUrl: (a) => `https://aurorascan.dev/address/${a}`,
    aliases: ["aurora"],
    cmcPlatformNames: ["Aurora"],
  },
  {
    key: "ronin",
    label: "Ronin",
    viemChain: ronin,
    rpcEnvVar: "RONIN_RPC_URL",
    defaultRpcUrls: ["https://api.roninchain.com/rpc"],
    explorerTxUrl: (h) => `https://app.roninchain.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://app.roninchain.com/address/${a}`,
    aliases: ["ronin"],
    cmcPlatformNames: ["Ronin"],
  },
  {
    key: "boba",
    label: "Boba Network",
    viemChain: boba,
    rpcEnvVar: "BOBA_RPC_URL",
    defaultRpcUrls: ["https://mainnet.boba.network"],
    explorerTxUrl: (h) => `https://bobascan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://bobascan.com/address/${a}`,
    aliases: ["boba"],
    cmcPlatformNames: ["Boba Network"],
  },
  {
    key: "tron",
    label: "Tron",
    viemChain: tron,
    rpcEnvVar: "TRON_RPC_URL",
    // Tron is not EVM, but its node speaks Ethereum JSON-RPC and Hyperlane's
    // registry already gives its addresses in hex - so eth_call reaches it
    // and none of the non-EVM machinery is needed. Five warp routes for one
    // table entry.
    // /diag reaches TronGrid on one call and the report's several fail:
    // that is a rate limit, not an outage. A second endpoint costs nothing
    // and a chain that drops out of a report reads as "no liquidity here".
    defaultRpcUrls: ["https://api.trongrid.io/jsonrpc", "https://tron-rpc.publicnode.com"],
    explorerTxUrl: (h) => `https://tronscan.org/#/transaction/${h}`,
    explorerAddressUrl: (a) => `https://tronscan.org/#/address/${a}`,
    aliases: ["tron", "trx"],
    cmcPlatformNames: ["Tron", "Tron20", "TRC20"],
    // TronGrid without a key throttles hard: four routes read at once left
    // three of four failing on every run, while one at a time gets through.
    maxConcurrentReads: 1,
  },
  {
    key: "flare",
    label: "Flare Mainnet",
    viemChain: flare,
    rpcEnvVar: "FLARE_RPC_URL",
    defaultRpcUrls: ["https://flare-api.flare.network/ext/C/rpc"],
    explorerTxUrl: (h) => `https://flare-explorer.flare.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://flare-explorer.flare.network/address/${a}`,
    aliases: ["flare", "flaremainnet"],
    cmcPlatformNames: ["Flare Mainnet", "Flare"],
  },
  {
    key: "cronos",
    label: "Cronos Mainnet",
    viemChain: cronos,
    rpcEnvVar: "CRONOS_RPC_URL",
    defaultRpcUrls: ["https://evm.cronos.org"],
    explorerTxUrl: (h) => `https://explorer.cronos.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.cronos.org/address/${a}`,
    aliases: ["cronos", "cronosmainnet"],
    cmcPlatformNames: ["Cronos Mainnet", "Cronos"],
  },
  {
    key: "deprecatedrootstock",
    label: "Rootstock Mainnet",
    viemChain: rootstock,
    rpcEnvVar: "DEPRECATEDROOTSTOCK_RPC_URL",
    defaultRpcUrls: ["https://public-node.rsk.co"],
    explorerTxUrl: (h) => `https://explorer.rsk.co/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.rsk.co/address/${a}`,
    aliases: ["deprecatedrootstock", "rootstockmainnet"],
    cmcPlatformNames: ["Rootstock Mainnet", "Rootstock"],
  },
  {
    key: "xpla",
    label: "CONX Chain",
    viemChain: xpla,
    rpcEnvVar: "XPLA_RPC_URL",
    defaultRpcUrls: ["https://dimension-evm-rpc.xpla.dev"],
    explorerTxUrl: (h) => `https://explorer.conx.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.conx.xyz/address/${a}`,
    aliases: ["xpla", "conxchain"],
    cmcPlatformNames: ["CONX Chain", "CONX"],
  },
  {
    key: "telos",
    label: "Telos",
    viemChain: telos,
    rpcEnvVar: "TELOS_RPC_URL",
    defaultRpcUrls: ["https://rpc.telos.net"],
    explorerTxUrl: (h) => `https://www.teloscan.io//tx/${h}`,
    explorerAddressUrl: (a) => `https://www.teloscan.io//address/${a}`,
    aliases: ["telos"],
    cmcPlatformNames: ["Telos"],
  },
  {
    key: "lukso",
    label: "LUKSO",
    viemChain: lukso,
    rpcEnvVar: "LUKSO_RPC_URL",
    defaultRpcUrls: ["https://rpc.mainnet.lukso.network"],
    explorerTxUrl: (h) => `https://explorer.execution.mainnet.lukso.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.execution.mainnet.lukso.network/address/${a}`,
    aliases: ["lukso"],
    cmcPlatformNames: ["LUKSO"],
  },
  {
    key: "syscoin",
    label: "Syscoin Mainnet",
    viemChain: syscoin,
    rpcEnvVar: "SYSCOIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.syscoin.org"],
    explorerTxUrl: (h) => `https://explorer.syscoin.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.syscoin.org/address/${a}`,
    aliases: ["syscoin", "syscoinmainnet"],
    cmcPlatformNames: ["Syscoin Mainnet", "Syscoin"],
  },
  {
    key: "viction",
    label: "Viction",
    viemChain: viction,
    rpcEnvVar: "VICTION_RPC_URL",
    defaultRpcUrls: ["https://rpc.viction.xyz"],
    explorerTxUrl: (h) => `https://vicscan.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://vicscan.xyz/address/${a}`,
    aliases: ["viction"],
    cmcPlatformNames: ["Viction"],
  },
  {
    key: "shibarium",
    label: "Shibarium",
    viemChain: shibarium,
    rpcEnvVar: "SHIBARIUM_RPC_URL",
    defaultRpcUrls: ["https://rpc.shibrpc.com"],
    explorerTxUrl: (h) => `https://shibariumscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://shibariumscan.io/address/${a}`,
    aliases: ["shibarium"],
    cmcPlatformNames: ["Shibarium"],
  },
  {
    key: "fusemainnet",
    label: "Fuse",
    viemChain: fuse,
    rpcEnvVar: "FUSEMAINNET_RPC_URL",
    defaultRpcUrls: ["https://rpc.fuse.io"],
    explorerTxUrl: (h) => `https://explorer.fuse.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.fuse.io/address/${a}`,
    aliases: ["fusemainnet", "fuse"],
    cmcPlatformNames: ["Fuse"],
  },
  {
    key: "mantapacific",
    label: "Manta Pacific Mainnet",
    viemChain: manta,
    rpcEnvVar: "MANTAPACIFIC_RPC_URL",
    defaultRpcUrls: ["https://pacific-rpc.manta.network/http"],
    explorerTxUrl: (h) => `https://pacific-explorer.manta.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://pacific-explorer.manta.network/address/${a}`,
    aliases: ["mantapacific", "mantapacificmainnet"],
    cmcPlatformNames: ["Manta Pacific Mainnet", "Manta Pacific"],
  },
  {
    key: "eni",
    label: "ENI Mainnet",
    viemChain: eni,
    rpcEnvVar: "ENI_RPC_URL",
    defaultRpcUrls: ["https://rpc.eniac.network"],
    explorerTxUrl: (h) => `https://scan.eniac.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.eniac.network/address/${a}`,
    aliases: ["eni", "enimainnet"],
    cmcPlatformNames: ["ENI Mainnet", "ENI"],
  },
  {
    key: "hashkey",
    label: "HashKey Chain",
    viemChain: hashkey,
    rpcEnvVar: "HASHKEY_RPC_URL",
    defaultRpcUrls: ["https://mainnet.hsk.xyz"],
    explorerTxUrl: (h) => `https://hashkey.blockscout.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://hashkey.blockscout.com/address/${a}`,
    aliases: ["hashkey", "hashkeychain"],
    cmcPlatformNames: ["HashKey Chain", "HashKey"],
  },
  {
    key: "mint",
    label: "Mint Mainnet",
    viemChain: mint,
    rpcEnvVar: "MINT_RPC_URL",
    defaultRpcUrls: ["https://rpc.mintchain.io"],
    explorerTxUrl: (h) => `https://explorer.mintchain.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.mintchain.io/address/${a}`,
    aliases: ["mint", "mintmainnet"],
    cmcPlatformNames: ["Mint Mainnet", "Mint"],
  },
  {
    key: "opbnb",
    label: "opBNB",
    viemChain: opBNB,
    rpcEnvVar: "OPBNB_RPC_URL",
    defaultRpcUrls: ["https://opbnb-mainnet-rpc.bnbchain.org"],
    explorerTxUrl: (h) => `https://opbnb.bscscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://opbnb.bscscan.com/address/${a}`,
    aliases: ["opbnb"],
    cmcPlatformNames: ["opBNB"],
  },
  {
    key: "bsquared",
    label: "B2",
    viemChain: bsquared,
    rpcEnvVar: "BSQUARED_RPC_URL",
    defaultRpcUrls: ["https://rpc.bsquared.network"],
    explorerTxUrl: (h) => `https://explorer.bsquared.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.bsquared.network/address/${a}`,
    aliases: ["bsquared", "b2"],
    cmcPlatformNames: ["B2"],
  },
  {
    key: "lens",
    label: "Lens",
    viemChain: lens,
    rpcEnvVar: "LENS_RPC_URL",
    defaultRpcUrls: ["https://rpc.lens.xyz"],
    explorerTxUrl: (h) => `https://explorer.lens.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.lens.xyz/address/${a}`,
    aliases: ["lens"],
    cmcPlatformNames: ["Lens"],
  },
  {
    key: "tac",
    label: "TAC",
    viemChain: tac,
    rpcEnvVar: "TAC_RPC_URL",
    defaultRpcUrls: ["https://rpc.ankr.com/tac"],
    explorerTxUrl: (h) => `https://tac.blockscout.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://tac.blockscout.com/address/${a}`,
    aliases: ["tac"],
    cmcPlatformNames: ["TAC"],
  },
  {
    key: "fantom",
    label: "Fantom",
    viemChain: fantom,
    rpcEnvVar: "FANTOM_RPC_URL",
    defaultRpcUrls: ["https://250.rpc.thirdweb.com"],
    explorerTxUrl: (h) => `https://ftmscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://ftmscan.com/address/${a}`,
    aliases: ["fantom"],
    cmcPlatformNames: ["Fantom"],
  },
  {
    key: "kroma",
    label: "Kroma",
    viemChain: kroma,
    rpcEnvVar: "KROMA_RPC_URL",
    defaultRpcUrls: ["https://api.kroma.network"],
    explorerTxUrl: (h) => `https://blockscout.kroma.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://blockscout.kroma.network/address/${a}`,
    aliases: ["kroma"],
    cmcPlatformNames: ["Kroma"],
  },
  {
    key: "guru",
    label: "Guru Network Mainnet",
    viemChain: guruNetwork,
    rpcEnvVar: "GURU_RPC_URL",
    defaultRpcUrls: ["https://rpc-main.gurunetwork.ai", "https://rpc.gurunetwork.ai/archive/260"],
    explorerTxUrl: (h) => `https://scan.gurunetwork.ai/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.gurunetwork.ai/address/${a}`,
    aliases: ["guru", "gurunetworkmainnet"],
    cmcPlatformNames: ["Guru Network Mainnet", "Guru Network"],
  },
  {
    key: "orderly",
    label: "Orderly",
    viemChain: orderly,
    rpcEnvVar: "ORDERLY_RPC_URL",
    defaultRpcUrls: ["https://rpc.orderly.network"],
    explorerTxUrl: (h) => `https://explorer.orderly.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.orderly.network/address/${a}`,
    aliases: ["orderly"],
    cmcPlatformNames: ["Orderly"],
  },
  {
    key: "filecoin",
    label: "Filecoin Mainnet",
    viemChain: filecoin,
    rpcEnvVar: "FILECOIN_RPC_URL",
    defaultRpcUrls: ["https://api.node.glif.io/rpc/v1"],
    explorerTxUrl: (h) => `https://filfox.info/en/tx/${h}`,
    explorerAddressUrl: (a) => `https://filfox.info/en/address/${a}`,
    aliases: ["filecoin", "filecoinmainnet"],
    cmcPlatformNames: ["Filecoin Mainnet", "Filecoin"],
  },
  {
    key: "molten",
    label: "Shape",
    viemChain: shape,
    rpcEnvVar: "MOLTEN_RPC_URL",
    defaultRpcUrls: ["https://mainnet.shape.network"],
    explorerTxUrl: (h) => `https://shapescan.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://shapescan.xyz/address/${a}`,
    aliases: ["molten", "shape"],
    cmcPlatformNames: ["Shape"],
  },
  {
    key: "pulsechain",
    label: "PulseChain",
    viemChain: pulsechain,
    rpcEnvVar: "PULSECHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.pulsechain.com"],
    explorerTxUrl: (h) => `https://ipfs.scan.pulsechain.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://ipfs.scan.pulsechain.com/address/${a}`,
    aliases: ["pulsechain"],
    cmcPlatformNames: ["PulseChain"],
  },
  {
    key: "astar",
    label: "Astar",
    viemChain: astar,
    rpcEnvVar: "ASTAR_RPC_URL",
    defaultRpcUrls: ["https://astar.api.onfinality.io/public"],
    explorerTxUrl: (h) => `https://astar.subscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://astar.subscan.io/address/${a}`,
    aliases: ["astar"],
    cmcPlatformNames: ["Astar"],
  },
  {
    key: "redstone",
    label: "Redstone",
    viemChain: redstone,
    rpcEnvVar: "REDSTONE_RPC_URL",
    defaultRpcUrls: ["https://rpc.redstonechain.com"],
    explorerTxUrl: (h) => `https://explorer.redstone.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.redstone.xyz/address/${a}`,
    aliases: ["redstone"],
    cmcPlatformNames: ["Redstone"],
  },
  {
    key: "matchain",
    label: "Matchain",
    viemChain: matchain,
    rpcEnvVar: "MATCHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.matchain.io"],
    explorerTxUrl: (h) => `https://matchscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://matchscan.io/address/${a}`,
    aliases: ["matchain"],
    cmcPlatformNames: ["Matchain"],
  },
  {
    key: "eden",
    label: "Eden",
    viemChain: eden,
    rpcEnvVar: "EDEN_RPC_URL",
    defaultRpcUrls: ["https://rpc.eden.gateway.fm"],
    explorerTxUrl: (h) => `https://eden.blockscout.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://eden.blockscout.com/address/${a}`,
    aliases: ["eden"],
    cmcPlatformNames: ["Eden"],
  },
  {
    key: "deprecatedflow",
    label: "Flow EVM Mainnet",
    viemChain: flowMainnet,
    rpcEnvVar: "DEPRECATEDFLOW_RPC_URL",
    defaultRpcUrls: ["https://mainnet.evm.nodes.onflow.org"],
    explorerTxUrl: (h) => `https://evm.flowscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://evm.flowscan.io/address/${a}`,
    aliases: ["deprecatedflow", "flowevmmainnet"],
    cmcPlatformNames: ["Flow EVM Mainnet", "Flow EVM"],
  },
  {
    key: "acala",
    label: "Acala",
    viemChain: acala,
    rpcEnvVar: "ACALA_RPC_URL",
    defaultRpcUrls: ["https://eth-rpc-acala.aca-api.network"],
    explorerTxUrl: (h) => `https://blockscout.acala.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://blockscout.acala.network/address/${a}`,
    aliases: ["acala"],
    cmcPlatformNames: ["Acala"],
  },
  {
    key: "subtensor",
    label: "Subtensor EVM",
    viemChain: subtensorEvm,
    rpcEnvVar: "SUBTENSOR_RPC_URL",
    defaultRpcUrls: ["https://lite.chain.opentensor.ai"],
    explorerTxUrl: (h) => `https://evm.taostats.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://evm.taostats.io/address/${a}`,
    aliases: ["subtensor", "subtensorevm"],
    cmcPlatformNames: ["Subtensor EVM"],
  },
  {
    key: "stable",
    label: "Stable Mainnet",
    viemChain: stable,
    rpcEnvVar: "STABLE_RPC_URL",
    defaultRpcUrls: ["https://rpc.stable.xyz"],
    explorerTxUrl: (h) => `https://stablescan.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://stablescan.xyz/address/${a}`,
    aliases: ["stable", "stablemainnet"],
    cmcPlatformNames: ["Stable Mainnet", "Stable"],
  },
  {
    key: "conflux",
    label: "Conflux eSpace",
    viemChain: confluxESpace,
    rpcEnvVar: "CONFLUX_RPC_URL",
    defaultRpcUrls: ["https://evm.confluxrpc.com"],
    explorerTxUrl: (h) => `https://evm.confluxscan.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://evm.confluxscan.org/address/${a}`,
    aliases: ["conflux", "confluxespace"],
    cmcPlatformNames: ["Conflux eSpace"],
  },
  {
    key: "metis",
    label: "Metis",
    viemChain: metis,
    rpcEnvVar: "METIS_RPC_URL",
    defaultRpcUrls: ["https://metis.rpc.hypersync.xyz", "https://metis-pokt.nodies.app", "https://api.blockeden.xyz/metis/67nCBdZQSH9z3YqDDjdm", "https://metis-andromeda.rpc.thirdweb.com", "https://metis-andromeda.gateway.tenderly.co", "https://metis.api.onfinality.io/public", "https://andromeda.metis.io/?owner=1088", "https://metis-mainnet.public.blastapi.io"],
    explorerTxUrl: (h) => `https://explorer.metis.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.metis.io/address/${a}`,
    aliases: ["metis"],
    cmcPlatformNames: ["Metis"],
  },
  {
    key: "polygonzkevm",
    label: "Polygon zkEVM",
    viemChain: polygonZkEvm,
    rpcEnvVar: "POLYGONZKEVM_RPC_URL",
    defaultRpcUrls: ["https://zkevm-rpc.com"],
    explorerTxUrl: (h) => `https://zkevm.polygonscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://zkevm.polygonscan.com/address/${a}`,
    aliases: ["polygonzkevm"],
    cmcPlatformNames: ["Polygon zkEVM"],
  },
  {
    key: "coredao",
    label: "Core Dao",
    viemChain: coreDao,
    rpcEnvVar: "COREDAO_RPC_URL",
    defaultRpcUrls: ["https://rpc.coredao.org"],
    explorerTxUrl: (h) => `https://scan.coredao.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.coredao.org/address/${a}`,
    aliases: ["coredao"],
    cmcPlatformNames: ["Core Dao"],
  },
  {
    key: "moonriver",
    label: "Moonriver",
    viemChain: moonriver,
    rpcEnvVar: "MOONRIVER_RPC_URL",
    defaultRpcUrls: ["https://rpc.api.moonriver.moonbeam.network"],
    explorerTxUrl: (h) => `https://moonriver.moonscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://moonriver.moonscan.io/address/${a}`,
    aliases: ["moonriver"],
    cmcPlatformNames: ["Moonriver"],
  },
  {
    key: "vana",
    label: "Vana",
    viemChain: vana,
    rpcEnvVar: "VANA_RPC_URL",
    defaultRpcUrls: ["https://rpc.vana.org/"],
    explorerTxUrl: (h) => `https://vanascan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://vanascan.io/address/${a}`,
    aliases: ["vana"],
    cmcPlatformNames: ["Vana"],
  },
  {
    key: "story",
    label: "Data Network",
    viemChain: story,
    rpcEnvVar: "STORY_RPC_URL",
    defaultRpcUrls: ["https://mainnet.datarpc.io"],
    explorerTxUrl: (h) => `https://datanetscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://datanetscan.io/address/${a}`,
    aliases: ["story", "datanetwork"],
    cmcPlatformNames: ["Data Network"],
  },
  {
    key: "tenet",
    label: "Tenet",
    viemChain: tenet,
    rpcEnvVar: "TENET_RPC_URL",
    defaultRpcUrls: ["https://rpc.tenet.org"],
    explorerTxUrl: (h) => `https://tenetscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://tenetscan.io/address/${a}`,
    aliases: ["tenet"],
    cmcPlatformNames: ["Tenet"],
  },
  {
    key: "gravity",
    label: "Gravity Alpha Mainnet",
    viemChain: gravity,
    rpcEnvVar: "GRAVITY_RPC_URL",
    defaultRpcUrls: ["https://rpc.gravity.xyz"],
    explorerTxUrl: (h) => `https://explorer.gravity.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.gravity.xyz/address/${a}`,
    aliases: ["gravity", "gravityalphamainnet"],
    cmcPlatformNames: ["Gravity Alpha Mainnet", "Gravity Alpha"],
  },
  {
    key: "kiichain",
    label: "KiiChain",
    viemChain: kii,
    rpcEnvVar: "KIICHAIN_RPC_URL",
    defaultRpcUrls: ["https://json-rpc.kiivalidator.com"],
    explorerTxUrl: (h) => `https://explorer.kiichain.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.kiichain.io/address/${a}`,
    aliases: ["kiichain"],
    cmcPlatformNames: ["KiiChain"],
  },
  {
    key: "lightlinkphoenixmainnet",
    label: "LightLink Phoenix Mainnet",
    viemChain: lightlinkPhoenix,
    rpcEnvVar: "LIGHTLINKPHOENIXMAINNET_RPC_URL",
    defaultRpcUrls: ["https://replicator.phoenix.lightlink.io/rpc/v1"],
    explorerTxUrl: (h) => `https://phoenix.lightlink.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://phoenix.lightlink.io/address/${a}`,
    aliases: ["lightlinkphoenixmainnet"],
    cmcPlatformNames: ["LightLink Phoenix Mainnet", "LightLink Phoenix"],
  },
  {
    key: "krown",
    label: "Krown",
    viemChain: krown,
    rpcEnvVar: "KROWN_RPC_URL",
    defaultRpcUrls: ["https://mainnet.krown.network"],
    explorerTxUrl: (h) => `https://explorer.krown.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.krown.network/address/${a}`,
    aliases: ["krown"],
    cmcPlatformNames: ["Krown"],
  },
  {
    key: "dogechain",
    label: "Dogechain",
    viemChain: dogechain,
    rpcEnvVar: "DOGECHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.dogechain.dog"],
    explorerTxUrl: (h) => `https://explorer.dogechain.dog/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.dogechain.dog/address/${a}`,
    aliases: ["dogechain"],
    cmcPlatformNames: ["Dogechain"],
  },
  {
    key: "snaxchain",
    label: "SnaxChain",
    viemChain: snax,
    rpcEnvVar: "SNAXCHAIN_RPC_URL",
    defaultRpcUrls: ["https://mainnet.snaxchain.io"],
    explorerTxUrl: (h) => `https://explorer.snaxchain.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.snaxchain.io/address/${a}`,
    aliases: ["snaxchain"],
    cmcPlatformNames: ["SnaxChain"],
  },
  {
    key: "kava",
    label: "Kava EVM",
    viemChain: kava,
    rpcEnvVar: "KAVA_RPC_URL",
    defaultRpcUrls: ["https://evm.kava.io"],
    explorerTxUrl: (h) => `https://kavascan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://kavascan.com/address/${a}`,
    aliases: ["kava", "kavaevm"],
    cmcPlatformNames: ["Kava EVM"],
  },
  {
    key: "inevm",
    label: "inEVM Mainnet",
    viemChain: inEVM,
    rpcEnvVar: "INEVM_RPC_URL",
    defaultRpcUrls: ["https://mainnet.rpc.inevm.com/http"],
    explorerTxUrl: (h) => `https://inevm.calderaexplorer.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://inevm.calderaexplorer.xyz/address/${a}`,
    aliases: ["inevm", "inevmmainnet"],
    cmcPlatformNames: ["inEVM Mainnet", "inEVM"],
  },
  {
    key: "abstract",
    label: "Abstract",
    viemChain: abstract,
    rpcEnvVar: "ABSTRACT_RPC_URL",
    defaultRpcUrls: ["https://api.mainnet.abs.xyz"],
    explorerTxUrl: (h) => `https://abscan.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://abscan.org/address/${a}`,
    aliases: ["abstract"],
    cmcPlatformNames: ["Abstract"],
  },
  {
    key: "morph",
    label: "Morph",
    viemChain: morph,
    rpcEnvVar: "MORPH_RPC_URL",
    defaultRpcUrls: ["https://rpc.morphl2.io"],
    explorerTxUrl: (h) => `https://explorer.morphl2.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.morphl2.io/address/${a}`,
    aliases: ["morph"],
    cmcPlatformNames: ["Morph"],
  },
  {
    key: "peaq",
    label: "Peaq",
    viemChain: peaq,
    rpcEnvVar: "PEAQ_RPC_URL",
    defaultRpcUrls: ["https://quicknode1.peaq.xyz", "https://quicknode2.peaq.xyz", "https://quicknode3.peaq.xyz"],
    explorerTxUrl: (h) => `https://peaq.subscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://peaq.subscan.io/address/${a}`,
    aliases: ["peaq"],
    cmcPlatformNames: ["Peaq"],
  },
  {
    key: "botanix",
    label: "Botanix",
    viemChain: botanix,
    rpcEnvVar: "BOTANIX_RPC_URL",
    defaultRpcUrls: ["https://rpc.botanixlabs.com"],
    explorerTxUrl: (h) => `https://botanixscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://botanixscan.io/address/${a}`,
    aliases: ["botanix"],
    cmcPlatformNames: ["Botanix"],
  },
  {
    key: "citrea",
    label: "Citrea Mainnet",
    viemChain: citrea,
    rpcEnvVar: "CITREA_RPC_URL",
    defaultRpcUrls: ["https://rpc.mainnet.citrea.xyz"],
    explorerTxUrl: (h) => `https://explorer.mainnet.citrea.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.mainnet.citrea.xyz/address/${a}`,
    aliases: ["citrea", "citreamainnet"],
    cmcPlatformNames: ["Citrea Mainnet", "Citrea"],
  },
  {
    key: "merlin",
    label: "Merlin",
    viemChain: merlin,
    rpcEnvVar: "MERLIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.merlinchain.io"],
    explorerTxUrl: (h) => `https://scan.merlinchain.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.merlinchain.io/address/${a}`,
    aliases: ["merlin"],
    cmcPlatformNames: ["Merlin"],
  },
  {
    key: "tempo",
    label: "Tempo Mainnet",
    viemChain: tempo,
    rpcEnvVar: "TEMPO_RPC_URL",
    defaultRpcUrls: ["https://rpc.tempo.xyz"],
    explorerTxUrl: (h) => `https://explore.tempo.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explore.tempo.xyz/address/${a}`,
    aliases: ["tempo", "tempomainnet"],
    cmcPlatformNames: ["Tempo Mainnet", "Tempo"],
  },
  {
    key: "megaeth",
    label: "MegaETH",
    viemChain: megaeth,
    rpcEnvVar: "MEGAETH_RPC_URL",
    defaultRpcUrls: ["https://mainnet.megaeth.com/rpc"],
    explorerTxUrl: (h) => `https://mega.etherscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://mega.etherscan.io/address/${a}`,
    aliases: ["megaeth"],
    cmcPlatformNames: ["MegaETH"],
  },
  {
    key: "robinhood",
    label: "Robinhood Chain",
    viemChain: robinhood,
    rpcEnvVar: "ROBINHOOD_RPC_URL",
    defaultRpcUrls: ["https://rpc.mainnet.chain.robinhood.com"],
    explorerTxUrl: (h) => `https://robinhoodchain.blockscout.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://robinhoodchain.blockscout.com/address/${a}`,
    aliases: ["robinhood", "robinhoodchain"],
    cmcPlatformNames: ["Robinhood Chain", "Robinhood"],
  },
  {
    key: "somnia",
    label: "Somnia",
    viemChain: somnia,
    rpcEnvVar: "SOMNIA_RPC_URL",
    defaultRpcUrls: ["https://api.infra.mainnet.somnia.network"],
    explorerTxUrl: (h) => `https://explorer.somnia.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.somnia.network/address/${a}`,
    aliases: ["somnia"],
    cmcPlatformNames: ["Somnia"],
  },
  {
    key: "mantra",
    label: "MANTRA EVM",
    viemChain: mantraEVM,
    rpcEnvVar: "MANTRA_RPC_URL",
    defaultRpcUrls: ["https://evm.mantrachain.io"],
    explorerTxUrl: (h) => `https://blockscout.mantrascan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://blockscout.mantrascan.io/address/${a}`,
    aliases: ["mantra", "mantraevm"],
    cmcPlatformNames: ["MANTRA EVM"],
  },
  {
    key: "bouncebit",
    label: "BounceBit Mainnet",
    viemChain: bounceBit,
    rpcEnvVar: "BOUNCEBIT_RPC_URL",
    defaultRpcUrls: ["https://fullnode-mainnet.bouncebitapi.com"],
    explorerTxUrl: (h) => `https://bbscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://bbscan.io/address/${a}`,
    aliases: ["bouncebit", "bouncebitmainnet"],
    cmcPlatformNames: ["BounceBit Mainnet", "BounceBit"],
  },
  {
    key: "nibiru",
    label: "Nibiru",
    viemChain: nibiru,
    rpcEnvVar: "NIBIRU_RPC_URL",
    defaultRpcUrls: ["https://evm-rpc.nibiru.fi"],
    explorerTxUrl: (h) => `https://nibiscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://nibiscan.io/address/${a}`,
    aliases: ["nibiru"],
    cmcPlatformNames: ["Nibiru"],
  },
  {
    key: "zetachain",
    label: "ZetaChain",
    viemChain: zetachain,
    rpcEnvVar: "ZETACHAIN_RPC_URL",
    defaultRpcUrls: ["https://zetachain-evm.blockpi.network/v1/rpc/public"],
    explorerTxUrl: (h) => `https://zetascan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://zetascan.com/address/${a}`,
    aliases: ["zetachain"],
    cmcPlatformNames: ["ZetaChain"],
  },
  {
    key: "cyber",
    label: "Cyber",
    viemChain: cyber,
    rpcEnvVar: "CYBER_RPC_URL",
    defaultRpcUrls: ["https://cyber.alt.technology"],
    explorerTxUrl: (h) => `https://cyberscan.co/tx/${h}`,
    explorerAddressUrl: (a) => `https://cyberscan.co/address/${a}`,
    aliases: ["cyber"],
    cmcPlatformNames: ["Cyber"],
  },
  {
    key: "canto",
    label: "Canto",
    viemChain: canto,
    rpcEnvVar: "CANTO_RPC_URL",
    defaultRpcUrls: ["https://canto.gravitychain.io"],
    explorerTxUrl: (h) => `https://tuber.build/tx/${h}`,
    explorerAddressUrl: (a) => `https://tuber.build/address/${a}`,
    aliases: ["canto"],
    cmcPlatformNames: ["Canto"],
  },
  {
    key: "kinto",
    label: "Kinto Mainnet",
    viemChain: kinto,
    rpcEnvVar: "KINTO_RPC_URL",
    defaultRpcUrls: ["https://rpc.kinto.xyz/http"],
    explorerTxUrl: (h) => `https://explorer.kinto.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.kinto.xyz/address/${a}`,
    aliases: ["kinto", "kintomainnet"],
    cmcPlatformNames: ["Kinto Mainnet", "Kinto"],
  },
  {
    key: "deprecatedpolynomial",
    label: "Polynomial",
    viemChain: polynomial,
    rpcEnvVar: "DEPRECATEDPOLYNOMIAL_RPC_URL",
    defaultRpcUrls: ["https://rpc.polynomial.fi"],
    explorerTxUrl: (h) => `https://polynomialscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://polynomialscan.io/address/${a}`,
    aliases: ["deprecatedpolynomial", "polynomial"],
    cmcPlatformNames: ["Polynomial"],
  },
  {
    key: "kaia",
    label: "Kaia",
    viemChain: kaia,
    rpcEnvVar: "KAIA_RPC_URL",
    defaultRpcUrls: ["https://public-en.node.kaia.io"],
    explorerTxUrl: (h) => `https://kaiascan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://kaiascan.io/address/${a}`,
    aliases: ["kaia"],
    cmcPlatformNames: ["Kaia"],
  },
  {
    key: "b3",
    label: "B3",
    viemChain: b3,
    rpcEnvVar: "B3_RPC_URL",
    defaultRpcUrls: ["https://mainnet-rpc.b3.fun/http"],
    explorerTxUrl: (h) => `https://explorer.b3.fun/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.b3.fun/address/${a}`,
    aliases: ["b3"],
    cmcPlatformNames: ["B3"],
  },
  {
    key: "evmos",
    label: "Evmos",
    viemChain: evmos,
    rpcEnvVar: "EVMOS_RPC_URL",
    defaultRpcUrls: ["https://eth.bd.evmos.org:8545"],
    explorerTxUrl: (h) => `https://escan.live/tx/${h}`,
    explorerAddressUrl: (a) => `https://escan.live/address/${a}`,
    aliases: ["evmos"],
    cmcPlatformNames: ["Evmos"],
  },
  {
    key: "deprecatedimmutablezkevm",
    label: "Immutable zkEVM",
    viemChain: immutableZkEvm,
    rpcEnvVar: "DEPRECATEDIMMUTABLEZKEVM_RPC_URL",
    defaultRpcUrls: ["https://rpc.immutable.com"],
    explorerTxUrl: (h) => `https://explorer.immutable.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.immutable.com/address/${a}`,
    aliases: ["deprecatedimmutablezkevm", "immutablezkevm"],
    cmcPlatformNames: ["Immutable zkEVM"],
  },
  {
    key: "fluent",
    label: "Fluent",
    viemChain: fluent,
    rpcEnvVar: "FLUENT_RPC_URL",
    defaultRpcUrls: ["https://rpc.fluent.xyz"],
    explorerTxUrl: (h) => `https://fluentscan.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://fluentscan.xyz/address/${a}`,
    aliases: ["fluent"],
    cmcPlatformNames: ["Fluent"],
  },
  {
    key: "apechain",
    label: "ApeChain",
    viemChain: apeChain,
    rpcEnvVar: "APECHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.apechain.com/http"],
    explorerTxUrl: (h) => `https://apescan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://apescan.io/address/${a}`,
    aliases: ["apechain"],
    cmcPlatformNames: ["ApeChain"],
  },
  {
    key: "funki",
    label: "Funki",
    viemChain: funkiMainnet,
    rpcEnvVar: "FUNKI_RPC_URL",
    defaultRpcUrls: ["https://rpc-mainnet.funkichain.com"],
    explorerTxUrl: (h) => `https://funkiscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://funkiscan.io/address/${a}`,
    aliases: ["funki"],
    cmcPlatformNames: ["Funki"],
  },
  {
    key: "adichain",
    label: "ADI_Chain",
    viemChain: adi,
    rpcEnvVar: "ADICHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.adifoundation.ai"],
    explorerTxUrl: (h) => `https://explorer.adifoundation.ai/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.adifoundation.ai/address/${a}`,
    aliases: ["adichain"],
    cmcPlatformNames: ["ADI_Chain"],
  },
  {
    key: "igra",
    label: "Igra Network",
    viemChain: igra,
    rpcEnvVar: "IGRA_RPC_URL",
    defaultRpcUrls: ["https://rpc.igralabs.com:8545"],
    explorerTxUrl: (h) => `https://explorer.igralabs.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.igralabs.com/address/${a}`,
    aliases: ["igra", "igranetwork"],
    cmcPlatformNames: ["Igra Network"],
  },
  {
    key: "alephzeroevmmainnet",
    label: "Aleph Zero",
    viemChain: alephZero,
    rpcEnvVar: "ALEPHZEROEVMMAINNET_RPC_URL",
    defaultRpcUrls: ["https://rpc.alephzero.raas.gelato.cloud"],
    explorerTxUrl: (h) => `https://evm-explorer.alephzero.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://evm-explorer.alephzero.org/address/${a}`,
    aliases: ["alephzeroevmmainnet", "alephzero"],
    cmcPlatformNames: ["Aleph Zero"],
  },
  {
    key: "arbitrumnova",
    label: "Arbitrum Nova",
    viemChain: arbitrumNova,
    rpcEnvVar: "ARBITRUMNOVA_RPC_URL",
    defaultRpcUrls: ["https://nova.arbitrum.io/rpc"],
    explorerTxUrl: (h) => `https://nova.arbiscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://nova.arbiscan.io/address/${a}`,
    aliases: ["arbitrumnova"],
    cmcPlatformNames: ["Arbitrum Nova"],
  },
  {
    key: "hemi",
    label: "Hemi",
    viemChain: hemi,
    rpcEnvVar: "HEMI_RPC_URL",
    defaultRpcUrls: ["https://rpc.hemi.network/rpc"],
    explorerTxUrl: (h) => `https://explorer.hemi.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.hemi.xyz/address/${a}`,
    aliases: ["hemi"],
    cmcPlatformNames: ["Hemi"],
  },
  {
    key: "sophon",
    label: "Sophon",
    viemChain: sophon,
    rpcEnvVar: "SOPHON_RPC_URL",
    defaultRpcUrls: ["https://rpc.sophon.xyz"],
    explorerTxUrl: (h) => `https://explorer.sophon.xyz/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.sophon.xyz/address/${a}`,
    aliases: ["sophon"],
    cmcPlatformNames: ["Sophon"],
  },
  {
    key: "electroneum",
    label: "Electroneum Mainnet",
    viemChain: electroneum,
    rpcEnvVar: "ELECTRONEUM_RPC_URL",
    defaultRpcUrls: ["https://rpc.electroneum.com"],
    explorerTxUrl: (h) => `https://blockexplorer.electroneum.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://blockexplorer.electroneum.com/address/${a}`,
    aliases: ["electroneum", "electroneummainnet"],
    cmcPlatformNames: ["Electroneum Mainnet", "Electroneum"],
  },
  {
    key: "deprecatedsuperposition",
    label: "Superposition",
    viemChain: superposition,
    rpcEnvVar: "DEPRECATEDSUPERPOSITION_RPC_URL",
    defaultRpcUrls: ["https://rpc.superposition.so"],
    explorerTxUrl: (h) => `https://explorer.superposition.so/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.superposition.so/address/${a}`,
    aliases: ["deprecatedsuperposition", "superposition"],
    cmcPlatformNames: ["Superposition"],
  },
  {
    key: "treasure",
    label: "Treasure",
    viemChain: treasure,
    rpcEnvVar: "TREASURE_RPC_URL",
    defaultRpcUrls: ["https://rpc.treasure.lol"],
    explorerTxUrl: (h) => `https://treasurescan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://treasurescan.io/address/${a}`,
    aliases: ["treasure"],
    cmcPlatformNames: ["Treasure"],
  },
  {
    key: "chilizmainnet",
    label: "Chiliz Chain",
    viemChain: chiliz,
    rpcEnvVar: "CHILIZMAINNET_RPC_URL",
    defaultRpcUrls: ["https://rpc.chiliz.com"],
    explorerTxUrl: (h) => `https://scan.chiliz.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.chiliz.com/address/${a}`,
    aliases: ["chilizmainnet", "chilizchain"],
    cmcPlatformNames: ["Chiliz Chain", "Chiliz"],
  },
  {
    key: "sova",
    label: "Sova",
    viemChain: sova,
    rpcEnvVar: "SOVA_RPC_URL",
    defaultRpcUrls: ["https://rpc.sova.io"],
    explorerTxUrl: (h) => `https://explorer.sova.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.sova.io/address/${a}`,
    aliases: ["sova"],
    cmcPlatformNames: ["Sova"],
  },
  {
    key: "real",
    label: "re.al",
    viemChain: real,
    rpcEnvVar: "REAL_RPC_URL",
    defaultRpcUrls: ["https://rpc.realforreal.gelato.digital"],
    explorerTxUrl: (h) => `https://explorer.re.al/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.re.al/address/${a}`,
    aliases: ["real"],
    cmcPlatformNames: ["re.al"],
  },
  {
    key: "bitlayer",
    label: "Bitlayer Mainnet",
    viemChain: bitlayer,
    rpcEnvVar: "BITLAYER_RPC_URL",
    defaultRpcUrls: ["https://rpc.bitlayer.org"],
    explorerTxUrl: (h) => `https://www.btrscan.com/tx/${h}`,
    explorerAddressUrl: (a) => `https://www.btrscan.com/address/${a}`,
    aliases: ["bitlayer", "bitlayermainnet"],
    cmcPlatformNames: ["Bitlayer Mainnet", "Bitlayer"],
  },
  {
    key: "zeronetwork",
    label: "Zero Network",
    viemChain: zeroNetwork,
    rpcEnvVar: "ZERONETWORK_RPC_URL",
    defaultRpcUrls: ["https://rpc.zerion.io/v1/zero"],
    explorerTxUrl: (h) => `https://explorer.zero.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zero.network/address/${a}`,
    aliases: ["zeronetwork"],
    cmcPlatformNames: ["Zero Network"],
  },
  {
    key: "xai",
    label: "Xai Mainnet",
    viemChain: xai,
    rpcEnvVar: "XAI_RPC_URL",
    defaultRpcUrls: ["https://xai-chain.net/rpc"],
    explorerTxUrl: (h) => `https://explorer.xai-chain.net/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.xai-chain.net/address/${a}`,
    aliases: ["xai", "xaimainnet"],
    cmcPlatformNames: ["Xai Mainnet", "Xai"],
  },
  {
    key: "zklink",
    label: "zkLink Nova",
    viemChain: zkLinkNova,
    rpcEnvVar: "ZKLINK_RPC_URL",
    defaultRpcUrls: ["https://rpc.zklink.io"],
    explorerTxUrl: (h) => `https://explorer.zklink.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zklink.io/address/${a}`,
    aliases: ["zklink", "zklinknova"],
    cmcPlatformNames: ["zkLink Nova"],
  },
  {
    key: "forma",
    label: "Forma",
    viemChain: forma,
    rpcEnvVar: "FORMA_RPC_URL",
    defaultRpcUrls: ["https://rpc.forma.art"],
    explorerTxUrl: (h) => `https://explorer.forma.art/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.forma.art/address/${a}`,
    aliases: ["forma"],
    cmcPlatformNames: ["Forma"],
  },
  {
    key: "xrplevm",
    label: "XRPL EVM",
    viemChain: xrplevm,
    rpcEnvVar: "XRPLEVM_RPC_URL",
    defaultRpcUrls: ["https://rpc.xrplevm.org"],
    explorerTxUrl: (h) => `https://explorer.xrplevm.org/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.xrplevm.org/address/${a}`,
    aliases: ["xrplevm"],
    cmcPlatformNames: ["XRPL EVM"],
  },
  {
    key: "saakuru",
    label: "Saakuru Mainnet",
    viemChain: saakuru,
    rpcEnvVar: "SAAKURU_RPC_URL",
    defaultRpcUrls: ["https://rpc.saakuru.network"],
    explorerTxUrl: (h) => `https://explorer.saakuru.network/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.saakuru.network/address/${a}`,
    aliases: ["saakuru", "saakurumainnet"],
    cmcPlatformNames: ["Saakuru Mainnet", "Saakuru"],
  },
  {
    key: "zoramainnet",
    label: "Zora",
    viemChain: zora,
    rpcEnvVar: "ZORAMAINNET_RPC_URL",
    defaultRpcUrls: ["https://rpc.zora.energy"],
    explorerTxUrl: (h) => `https://explorer.zora.energy/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.zora.energy/address/${a}`,
    aliases: ["zoramainnet", "zora"],
    cmcPlatformNames: ["Zora"],
  },
  {
    key: "corn",
    label: "Corn",
    viemChain: corn,
    rpcEnvVar: "CORN_RPC_URL",
    defaultRpcUrls: ["https://21000000.rpc.thirdweb.com"],
    explorerTxUrl: (h) => `https://cornscan.io/tx/${h}`,
    explorerAddressUrl: (a) => `https://cornscan.io/address/${a}`,
    aliases: ["corn"],
    cmcPlatformNames: ["Corn"],
  },
  {
    key: "degenchain",
    label: "Degen",
    viemChain: degen,
    rpcEnvVar: "DEGENCHAIN_RPC_URL",
    defaultRpcUrls: ["https://rpc.degen.tips"],
    explorerTxUrl: (h) => `https://explorer.degen.tips/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.degen.tips/address/${a}`,
    aliases: ["degenchain", "degen"],
    cmcPlatformNames: ["Degen"],
  },
  {
    key: "ancient8",
    label: "Ancient8",
    viemChain: ancient8,
    rpcEnvVar: "ANCIENT8_RPC_URL",
    defaultRpcUrls: ["https://rpc.ancient8.gg"],
    explorerTxUrl: (h) => `https://scan.ancient8.gg/tx/${h}`,
    explorerAddressUrl: (a) => `https://scan.ancient8.gg/address/${a}`,
    aliases: ["ancient8"],
    cmcPlatformNames: ["Ancient8"],
  },
  {
    key: "lumia",
    label: "Lumia Mainnet",
    viemChain: lumiaMainnet,
    rpcEnvVar: "LUMIA_RPC_URL",
    defaultRpcUrls: ["https://mainnet-rpc.lumia.org"],
    explorerTxUrl: (h) => `https://explorer.lumia.org//tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.lumia.org//address/${a}`,
    aliases: ["lumia", "lumiamainnet"],
    cmcPlatformNames: ["Lumia Mainnet", "Lumia"],
  },
  {
    key: "harmony",
    label: "Harmony One",
    viemChain: harmonyOne,
    rpcEnvVar: "HARMONY_RPC_URL",
    defaultRpcUrls: ["https://1666600000.rpc.thirdweb.com"],
    explorerTxUrl: (h) => `https://explorer.harmony.one/tx/${h}`,
    explorerAddressUrl: (a) => `https://explorer.harmony.one/address/${a}`,
    aliases: ["harmony", "harmonyone"],
    cmcPlatformNames: ["Harmony One"],
  },
];

export type ChainKey = (typeof CHAINS)[number]["key"];

const byKey = new Map(CHAINS.map((c) => [c.key, c]));
const byAlias = new Map<string, ChainDef>();
for (const c of CHAINS) {
  for (const alias of c.aliases) byAlias.set(alias.toLowerCase(), c);
}

export function getChain(key: string): ChainDef | undefined {
  return byKey.get(key);
}

export function resolveChain(input: string): ChainDef | undefined {
  return byAlias.get(input.trim().toLowerCase());
}

export function allChainKeys(): string[] {
  return CHAINS.map((c) => c.key);
}


/**
 * Label and explorer for any chain the bot reads, EVM or not.
 *
 * getChain() deliberately answers only for EVM chains, because everything
 * that calls it needs `viemChain`. The report needs neither - it needs a
 * name and a link - so it asks this instead, and a Solana row renders like
 * any other rather than falling back to a bare chain key.
 */
export function chainMeta(chainKey: string): { label: string; explorerAddressUrl: (a: string) => string } | undefined {
  const evm = CHAINS.find((c) => c.key === chainKey);
  if (evm) return { label: evm.label, explorerAddressUrl: evm.explorerAddressUrl };

  const svm = SVM_CHAINS.find((c) => c.key === chainKey);
  if (svm) return { label: svm.label, explorerAddressUrl: svm.explorerAddressUrl };

  const cosmos = COSMOS_CHAINS.find((c) => c.key === chainKey);
  if (cosmos) return { label: cosmos.label, explorerAddressUrl: cosmos.explorerAddressUrl };

  const other = OTHER_CHAINS.find((c) => c.key === chainKey);
  if (other) return { label: other.label, explorerAddressUrl: other.explorerAddressUrl };

  return undefined;
}


/**
 * Resolves a chain the user typed, EVM or not.
 *
 * resolveChain() answers only for EVM chains because its callers need
 * `viemChain`. But a person typing "solana" after a ticker is naming a chain
 * the bot now reads, and telling them it is not connected - while the report
 * shows Solana rows two lines above - is simply wrong.
 */
export function resolveAnyChain(name: string): { key: string; label: string } | undefined {
  const evm = resolveChain(name);
  if (evm) return { key: evm.key, label: evm.label };

  const svm = resolveSvmChain(name);
  if (svm) return { key: svm.key, label: svm.label };

  const cosmos = resolveCosmosChain(name);
  if (cosmos) return { key: cosmos.key, label: cosmos.label };

  const other = resolveOtherChain(name);
  if (other) return { key: other.key, label: other.label };

  return undefined;
}
