/**
 * Extra public endpoints per chain id, tried after the one viem carries.
 *
 * Keyed by chain id, not by the bot's own name for a chain: it discovers
 * chains at runtime, and a chain it was never told about has no such name -
 * so keying by name gave every discovered chain an empty list.
 *
 * GENERATED FILE. Do not edit by hand: run \`npm run sync:rpcs\`.
 *
 * viem lists a single endpoint per chain. That is enough for the majors and
 * not enough for the long tail, where one refusal takes the whole chain out
 * of the report - and a missing chain reads as "no liquidity here", which is
 * the opposite of what it means.
 *
 * Sources: chainlist-rpcs@0.5.311, the data behind chainlist.org;
 * @hyperlane-xyz/registry, which a bridge operator keeps answering because
 * its relayers depend on it; and ethereum-lists/chains, the registry
 * chainid.network serves. Three of them because they disagree exactly where
 * it matters - both public lists had only dead hosts for Zero Network while
 * Hyperlane had two that answer - and a chain whose single entry is dead has
 * no endpoints at all.
 */
export const EXTRA_RPC_URLS_BY_CHAIN_ID: Record<number, string[]> = {
  1: ["https://lb.routeme.sh/rpc/evm/1", "https://one.valve.city/rpc/vk_demo/evm/1", "https://rpc.nodeflare.app/eth/public", "https://go.getblock.io/aefd01aa907c4805ba3c00a9e5b48c6b", "https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7", "https://rpc.ankr.com/eth/c4cc6a8c87ec30258076de433ab2cf3d834228aae3fc4d76087873e4fea11635", "https://public.1rpc.io/eth", "https://rpc.builder0x69.io"],
  2: ["https://lb.routeme.sh/rpc/evm/2", "https://node.eggs.cool", "https://node.expanse.tech"],
  7: ["https://lb.routeme.sh/rpc/evm/7", "https://rpc.dome.cloud", "https://rpc.thaichain.org"],
  8: ["https://rpc.octano.dev", "https://rpc.c8ntinuum.com", "https://rpc.c8ntinuum.io", "https://rpc.c8ntinuum.link"],
  9: ["https://rpc.quai.network/cyprus1"],
  10: ["https://lb.routeme.sh/rpc/evm/10", "https://rpc.nodeflare.app/op/public", "https://optimism-mainnet.public.blastapi.io", "https://public.1rpc.io/op", "https://optimism-public.nodies.app", "https://opt-mainnet.g.alchemy.com/v2/demo", "https://optimism.public.blockpi.network/v1/rpc/public", "https://optimism.api.onfinality.io/public"],
  11: ["https://lb.routeme.sh/rpc/evm/11", "https://api.metadium.com/dev", "https://api.metadium.com/prod"],
  14: ["https://lb.routeme.sh/rpc/evm/14", "https://flare-mainnet.gateway.tatum.io", "https://flare.drpc.org", "https://flare.solidifi.app/ext/C/rpc", "https://flare.rpc.thirdweb.com", "https://rpc.ankr.com/flare", "https://flare-bundler.etherspot.io", "https://01-gravelines-003-01.rpc.tatum.io/ext/bc/C/rpc"],
  15: ["https://lb.routeme.sh/rpc/evm/15", "https://prenet.diode.io:8443"],
  19: ["https://lb.routeme.sh/rpc/evm/19", "https://songbird-api.flare.network/ext/C/rpc", "https://rpc.ftso.au/songbird", "https://songbird.solidifi.app/ext/C/rpc", "https://flare-songbird.gateway.tatum.io", "https://01-gravelines-006-01.rpc.tatum.io/ext/bc/C/rpc", "https://01-vinthill-006-02.rpc.tatum.io/ext/bc/C/rpc", "https://02-tokyo-006-03.rpc.tatum.io/ext/bc/C/rpc"],
  20: ["https://lb.routeme.sh/rpc/evm/20", "https://api.elastos.io/esc", "https://api.trinity-tech.io/esc", "https://api2.elastos.io/esc", "https://api2.elastos.net/esc", "https://api2.elastos.io/eth", "https://api2.elastos.net/eth", "https://rpc.glidefinance.io"],
  24: ["https://rpc.kardiachain.io"],
  25: ["https://lb.routeme.sh/rpc/evm/25", "https://rpc.nodeflare.app/cronos/public", "https://cronos-rpc.elk.finance", "https://cronos-evm-rpc.publicnode.com", "https://public.1rpc.io/cro", "https://cronos.drpc.org", "https://rpc.vvs.finance", "https://mmf-rpc.xstaking.sg"],
  30: ["https://lb.routeme.sh/rpc/evm/30", "https://mycrypto.rsk.co", "https://rootstock.drpc.org", "https://rootstock-mainnet.public.blastapi.io", "https://rsk-mainnet.gateway.tatum.io", "https://rpc.mainnet.rootstock.io/kXhXHf6TnnfW1POvr4UT0YUvujmuju-M"],
  37: ["https://lb.routeme.sh/rpc/evm/37"],
  40: ["https://lb.routeme.sh/rpc/evm/40", "https://public.1rpc.io/telos/evm", "https://telos.drpc.org", "https://rpc.ankr.com/telos", "https://rpc.poolz.finance/telos"],
  42: ["https://lb.routeme.sh/rpc/evm/42", "https://rpc.lukso.sigmacore.io", "https://42.rpc.thirdweb.com", "https://public-lukso.nownodes.io"],
  44: ["https://crab.api.onfinality.io/public", "https://crab-rpc.darwinia.network", "https://crab-rpc.dcdao.box"],
  46: ["https://lb.routeme.sh/rpc/evm/46", "https://rpc.darwinia.network", "https://darwinia-rpc.dcdao.box", "https://darwinia-rpc.dwellir.com", "https://darwinia.rpc.subquery.network/public"],
  47: ["https://aic.acria.ai"],
  50: ["https://lb.routeme.sh/rpc/evm/50", "https://rpc.xdcrpc.com", "https://rpc1.xinfin.network", "https://erpc.xinfin.network", "https://erpc.xdcrpc.com", "https://rpc.xdc.org", "https://rpc.xdc.network", "https://earpc.xinfin.network"],
  52: ["https://lb.routeme.sh/rpc/evm/52", "https://rpc.coinex.net", "https://rpc1.coinex.net", "https://rpc2.coinex.net", "https://rpc3.coinex.net", "https://rpc4.coinex.net"],
  56: ["https://lb.routeme.sh/rpc/evm/56", "https://rpc.nodeflare.app/bnb/public", "https://bsc-dataseed.bnbchain.org", "https://bsc.campioneinfrastructure.com", "https://bsc-dataseed1.defibit.io", "https://bsc-dataseed1.ninicoin.io", "https://bsc-dataseed2.defibit.io", "https://bsc-dataseed3.defibit.io"],
  57: ["https://lb.routeme.sh/rpc/evm/57", "https://rpc.ankr.com/syscoin", "https://syscoin-evm.publicnode.com", "https://syscoin.public-rpc.com", "https://57.rpc.thirdweb.com"],
  58: ["https://lb.routeme.sh/rpc/evm/58", "https://dappnode1.ont.io:10339", "https://dappnode2.ont.io:10339", "https://dappnode3.ont.io:10339", "https://dappnode4.ont.io:10339"],
  60: ["https://lb.routeme.sh/rpc/evm/60", "https://rpc.gochain.io"],
  61: ["https://lb.routeme.sh/rpc/evm/61", "https://etc.etcdesktop.com", "https://rpc.etcmc.xyz", "https://etc.rivet.link", "https://0xrpc.io/etc", "https://ethereum-classic-mainnet.gateway.tatum.io", "https://rpc.swiftnodes.io/rpc/etc", "https://besu-at.etc-network.info"],
  66: ["https://lb.routeme.sh/rpc/evm/66", "https://exchainrpc.okex.org", "https://oktc-mainnet.public.blastapi.io", "https://public.1rpc.io/oktc", "https://oktc.drpc.org", "https://okc-mainnet.gateway.pokt.network/v1/lb/6275309bea1b320039c893ff"],
  74: ["https://lb.routeme.sh/rpc/evm/74", "https://idchain.one/rpc"],
  81: ["https://lb.routeme.sh/rpc/evm/81", "https://rpc-1.japanopenchain.org:8545", "https://rpc-2.japanopenchain.org:8545", "https://rpc-3.japanopenchain.org"],
  82: ["https://lb.routeme.sh/rpc/evm/82", "https://rpc.meter.io", "https://rpc-meter.jellypool.xyz"],
  86: ["https://lb.routeme.sh/rpc/evm/86", "https://evm.gatenode.cc"],
  88: ["https://viction.drpc.org", "https://lb.routeme.sh/rpc/evm/88", "https://88.rpc.thirdweb.com"],
  94: ["https://lb.routeme.sh/rpc/evm/94", "https://rpc.swissdlt.ch"],
  96: ["https://lb.routeme.sh/rpc/evm/96", "https://rpc.bitkubchain.io"],
  98: ["https://lb.routeme.sh/rpc/evm/98", "https://sixnet-rpc-evm.sixprotocol.net"],
  100: ["https://lb.routeme.sh/rpc/evm/100", "https://xdai-archive.blockscout.com", "https://gnosis-public.nodies.app", "https://rpc.gnosis.gateway.fm", "https://gnosis-mainnet.public.blastapi.io", "https://rpc.ap-southeast-1.gateway.fm/v4/gnosis/non-archival/mainnet", "https://gnosis.api.onfinality.io/public", "https://gnosis.drpc.org"],
  103: ["https://lb.routeme.sh/rpc/evm/103", "https://seoul.worldland.foundation", "https://seoul2.worldland.foundation"],
  106: ["https://lb.routeme.sh/rpc/evm/106", "https://evmexplorer.velas.com/rpc", "https://explorer.velas.com/rpc"],
  108: ["https://lb.routeme.sh/rpc/evm/108", "https://mainnet-rpc.thundercore.com", "https://thundercore.drpc.org", "https://mainnet-rpc.thundertoken.net", "https://mainnet-rpc.thundercore.io"],
  109: ["https://shibarium.drpc.org", "https://www.shibrpc.com", "https://shib.nownodes.io"],
  112: ["https://lb.routeme.sh/rpc/evm/112", "https://coinbit-rpc-mainnet.chain.sbcrypto.app"],
  119: ["https://evmapi.nuls.io", "https://evmapi2.nuls.io"],
  122: ["https://lb.routeme.sh/rpc/evm/122", "https://fuse-public.nodies.app", "https://fuse-mainnet.chainstacklabs.com", "https://fuse.api.onfinality.io/public", "https://fuse.liquify.com", "https://fuse.drpc.org", "https://rpc.owlracle.info/fuse/70d38ce1826c4a60bb2a8e05a6c8b20f", "https://fuse.api.pocket.network"],
  123: ["https://lb.routeme.sh/rpc/evm/123", "https://rpc.fusespark.io"],
  130: ["https://lb.routeme.sh/rpc/evm/130", "https://rpc.nodeflare.app/unichain/public", "https://unichain.api.onfinality.io/public", "https://unichain-rpc.publicnode.com", "https://unichain.drpc.org", "https://unichain.therpc.io", "https://unichain-mainnet.gateway.tatum.io", "https://rpc.poolz.finance/unichain"],
  137: ["https://lb.routeme.sh/rpc/evm/137", "https://rpc.nodeflare.app/polygon/public", "https://rpc-mainnet.matic.quiknode.pro", "https://polygon-public.nodies.app", "https://polygon-mainnet.public.blastapi.io", "https://public.1rpc.io/matic", "https://polygon-mainnet.g.alchemy.com/v2/demo", "https://go.getblock.io/02667b699f05444ab2c64f9bff28f027"],
  138: ["https://rpc-http-pub.d-bis.org", "https://rpc.d-bis.org", "https://rpc2.d-bis.org", "https://rpc.public-0138.defi-oracle.io", "https://rpc.defi-oracle.io"],
  140: ["https://mainnet.eteria.io/v1"],
  143: ["https://lb.routeme.sh/rpc/evm/143", "https://monad-mainnet.api.onfinality.io/public", "https://monad-mainnet.drpc.org", "https://monad-mainnet-rpc.spidernode.net", "https://infra.originstake.com/monad/evm", "https://monad-mainnet.gateway.tatum.io", "https://monad-mainnet.rpc.sentio.xyz", "https://monad-rpc.huginn.tech"],
  146: ["https://lb.routeme.sh/rpc/evm/146", "https://rpc.nodeflare.app/sonic/public", "https://sonic.drpc.org", "https://rpc.ankr.com/sonic_mainnet", "https://sonic.api.onfinality.io/public", "https://sonic.therpc.io", "https://sonic-json-rpc.stakely.io", "https://sonic.api.pocket.network"],
  148: ["https://lb.routeme.sh/rpc/evm/148", "https://json-rpc.evm.shimmer.network"],
  151: ["https://governors.mainnet.redbelly.network", "https://rpc.ankr.com/redbelly_mainnet", "https://api.uniblock.dev/uni/v1/json-rpc?chainId=151"],
  166: ["https://mainnet.nomina.io"],
  168: ["https://lb.routeme.sh/rpc/evm/168", "https://eth-dataseed.aioz.network"],
  169: ["https://lb.routeme.sh/rpc/evm/169", "https://public.1rpc.io/manta", "https://manta-pacific-gascap.calderachain.xyz/http", "https://www.tencentcloud-rpc.com/v2/manta/manta-rpc", "https://r1.pacific.manta.systems/http", "https://manta.nirvanalabs.xyz/mantapublic", "https://manta-pacific.calderachain.xyz/http", "https://manta-pacific.drpc.org"],
  173: ["https://rpc1.eniac.network", "https://rpc2.eniac.network", "https://enirpc.com", "https://jp.enirpc.com", "https://jp.eniacrpc.net"],
  177: ["https://hashkey.drpc.org"],
  179: ["https://lb.routeme.sh/rpc/evm/179", "https://rpc.abeychain.com"],
  183: ["https://mainnet.ethernitychain.io"],
  185: ["https://global.rpc.mintchain.io", "https://asia.rpc.mintchain.io"],
  196: ["https://lb.routeme.sh/rpc/evm/196", "https://rpc.nodeflare.app/xlayer/public", "https://rpc.xlayer.tech", "https://endpoints.omniatech.io/v1/xlayer/mainnet/public", "https://xlayer.drpc.org", "https://rpc.ankr.com/xlayer", "https://xlayer.rpc.blxrbdn.com", "https://xlayer-mainnet.rpc.sentio.xyz"],
  199: ["https://lb.routeme.sh/rpc/evm/199", "https://rpc.bittorrentchain.io", "https://rpc.bt.io", "https://bittorrent.drpc.org"],
  204: ["https://lb.routeme.sh/rpc/evm/204", "https://opbnb.drpc.org", "https://opbnb-rpc.publicnode.com", "https://public.1rpc.io/opbnb", "https://opbnb-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f", "https://opbnb.therpc.io", "https://opbnb.api.pocket.network", "https://api-opbnb-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  223: ["https://lb.routeme.sh/rpc/evm/223", "https://b2-mainnet.alt.technology", "https://b2-mainnet-public.s.chainbase.com", "https://mainnet.b2-rpc.com", "https://b2-mainnet.rpc.sentio.xyz", "https://rpc.ankr.com/b2"],
  227: ["https://prom-rpc.eu-north-2.gateway.fm"],
  232: ["https://lb.routeme.sh/rpc/evm/232", "https://light-icy-dinghy.lens-mainnet.quiknode.pro", "https://lens-mainnet.g.alchemy.com/public", "https://lens.drpc.org"],
  239: ["https://lb.routeme.sh/rpc/evm/239", "https://tac.therpc.io", "https://tac.drpc.org", "https://rpc.tac.build"],
  240: ["https://lb.routeme.sh/rpc/evm/240", "https://cronos-zkevm-testnet.drpc.org", "https://testnet.zkevm.cronos.org"],
  242: ["https://rpcurl.mainnet.plgchain.com", "https://rpcurl.plgchain.blockchain.evmnode.online", "https://rpcurl.mainnet.plgchain.plinga.technology"],
  246: ["https://lb.routeme.sh/rpc/evm/246", "https://rpc.energyweb.org"],
  248: ["https://lb.routeme.sh/rpc/evm/248", "https://rpc.mainnet.oasys.games", "https://oasys.api.pocket.network"],
  250: ["https://lb.routeme.sh/rpc/evm/250", "https://rpcapi.fantom.network", "https://fantom-public.nodies.app", "https://rpc.ftm.tools", "https://rpc.fantom.network", "https://rpc2.fantom.network", "https://rpc3.fantom.network", "https://fantom-mainnet.public.blastapi.io"],
  251: ["https://rpc-api.glideprotocol.xyz/l1-rpc"],
  252: ["https://lb.routeme.sh/rpc/evm/252", "https://fraxtal.drpc.org", "https://fraxtal.gateway.tenderly.co", "https://node.histori.xyz/fraxtal-mainnet/8ry9f6t9dct1se2hlagxnd9n2a", "https://fraxtal.api.pocket.network", "https://rpc.swiftnodes.io/rpc/fraxtal", "https://frax-mainnet.rpc.sentio.xyz", "https://fraxtal-rpc.publicnode.com"],
  253: ["https://rpc-api.glideprotocol.xyz/l2-rpc"],
  254: ["https://mainnet-rpc.swanchain.org", "https://mainnet-rpc-01.swanchain.org", "https://mainnet-rpc-02.swanchain.org", "https://mainnet-rpc-03.swanchain.org", "https://mainnet-rpc-04.swanchain.org"],
  255: ["https://lb.routeme.sh/rpc/evm/255", "https://kroma.drpc.org", "https://rpc-kroma.rockx.com", "https://1rpc.io/kroma"],
  269: ["https://lb.routeme.sh/rpc/evm/269", "https://hpbnode.com"],
  273: ["https://xr1.calderachain.xyz/http"],
  288: ["https://lb.routeme.sh/rpc/evm/288", "https://boba-ethereum.gateway.tenderly.co", "https://gateway.tenderly.co/public/boba-ethereum", "https://public.1rpc.io/boba/eth", "https://boba-eth.drpc.org", "https://boba.api.pocket.network", "https://api-boba-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c", "https://replica.boba.network"],
  291: ["https://lb.routeme.sh/rpc/evm/291", "https://orderly.drpc.org"],
  295: ["https://lb.routeme.sh/rpc/evm/295", "https://hedera.linkpool.pro", "https://295.rpc.thirdweb.com", "https://mainnet.hedera.api.hgraph.io/rpc", "https://mainnet.hashio.io/api"],
  311: ["https://lb.routeme.sh/rpc/evm/311", "https://mainapi.omaxray.com", "https://mainapi.omaxscan.com"],
  314: ["https://lb.routeme.sh/rpc/evm/314", "https://api.node.glif.io", "https://node.filutils.com/rpc/v1", "https://rpc.ankr.com/filecoin", "https://filecoin.chainup.net/rpc/v1", "https://infura.sftproject.io/filecoin/rpc/v1", "https://api.chain.love/rpc/v1", "https://filecoin.drpc.org"],
  321: ["https://lb.routeme.sh/rpc/evm/321", "https://rpc-mainnet.kcc.network", "https://kcc.mytokenpocket.vip", "https://kcc-rpc.com", "https://services.tokenview.io/vipapi/nodeservice/kcs?apikey=qVHq2o6jpaakcw3lRstl", "https://kcs-mainnet.gateway.tatum.io", "https://public-rpc.blockpi.io/http/kcc"],
  324: ["https://lb.routeme.sh/rpc/evm/324", "https://li-fi-redirect.intustechno.workers.dev/rpc", "https://go.getblock.io/f76c09905def4618a34946bf71851542", "https://zksync.meowrpc.com", "https://zksync.drpc.org", "https://public.1rpc.io/zksync2-era", "https://endpoints.omniatech.io/v1/zksync-era/mainnet/public", "https://api.zan.top/zksync-mainnet"],
  336: ["https://lb.routeme.sh/rpc/evm/336", "https://rpc.shiden.astar.network:8545", "https://shiden.public.blastapi.io", "https://shiden-rpc.dwellir.com", "https://shiden.api.onfinality.io/public", "https://shiden.public.curie.radiumblock.co/http"],
  360: ["https://lb.routeme.sh/rpc/evm/360", "https://shape-mainnet.g.alchemy.com/public", "https://molten.calderachain.xyz/http"],
  361: ["https://lb.routeme.sh/rpc/evm/361", "https://eth-rpc-api.thetatoken.org/rpc"],
  369: ["https://lb.routeme.sh/rpc/evm/369", "https://rpc.gigatheminter.com", "https://rpc-pulsechain.g4mm4.io", "https://evex.cloud/pulserpc", "https://rpc.degenprotocol.io", "https://one.valve.city/rpc/vk_demo/evm/369", "https://pulsechain-rpc.publicnode.com", "https://rpc.owlracle.info/pulse/70d38ce1826c4a60bb2a8e05a6c8b20f"],
  375: ["https://rpc.zkxpla.io"],
  388: ["https://lb.routeme.sh/rpc/evm/388", "https://cronos-zkevm.drpc.org", "https://cronos-zkevm.rpc.sentio.xyz"],
  397: ["https://near.drpc.org", "https://near-mainnet.gateway.tatum.io", "https://eth-rpc.mainnet.near.org"],
  424: ["https://rpc.publicgoods.network"],
  463: ["https://lb.routeme.sh/rpc/evm/463", "https://mainnet-rpc.areum.network", "https://mainnet-rpc2.areum.network", "https://mainnet-rpc3.areum.network", "https://mainnet-rpc4.areum.network", "https://mainnet-rpc5.areum.network"],
  466: ["https://lb.routeme.sh/rpc/evm/466", "https://appchain.calderachain.xyz/http", "https://rpc.appchain.xyz/http"],
  478: ["https://rpc.form.network/http"],
  480: ["https://lb.routeme.sh/rpc/evm/480", "https://480.rpc.thirdweb.com", "https://worldchain-mainnet.gateway.tenderly.co", "https://sparkling-autumn-dinghy.worldchain-mainnet.quiknode.pro", "https://worldchain.drpc.org"],
  570: ["https://lb.routeme.sh/rpc/evm/570", "https://rpc.rollux.com", "https://rollux.rpc.syscoin.org", "https://rpc.ankr.com/rollux"],
  571: ["https://rpc.metatime.com"],
  589: ["https://ladyrpc.us/rpc"],
  592: ["https://lb.routeme.sh/rpc/evm/592", "https://evm.astar.network", "https://rpc.astar.network:8545", "https://astar.public.blastapi.io", "https://getblock.io/nodes/bsc", "https://public.1rpc.io/astr", "https://astar-mainnet.g.alchemy.com/v2/demo", "https://astar-rpc.dwellir.com"],
  626: ["https://mainnet.battlechain.com"],
  648: ["https://lb.routeme.sh/rpc/evm/648", "https://rpc-endurance.fusionist.io"],
  680: ["https://rpc.jasmyscan.net"],
  686: ["https://lb.routeme.sh/rpc/evm/686", "https://eth-rpc-karura.aca-staging.network", "https://rpc.evm.karura.network", "https://karura.api.onfinality.io/public", "https://eth-rpc-karura.aca-api.network"],
  690: ["https://lb.routeme.sh/rpc/evm/690"],
  698: ["https://lb.routeme.sh/rpc/evm/698", "https://rpc.ankr.com/matchain_mainnet"],
  721: ["https://rpc.lycanchain.com", "https://us-east.lycanchain.com", "https://us-west.lycanchain.com", "https://eu-north.lycanchain.com", "https://eu-west.lycanchain.com", "https://asia-southeast.lycanchain.com"],
  747: ["https://lb.routeme.sh/rpc/evm/747", "https://flow-mainnet.gateway.tatum.io"],
  753: ["https://rivalz.calderachain.xyz/http"],
  766: ["https://lb.routeme.sh/rpc/evm/766", "https://evm-rpc-ql1.foxxone.one", "https://evm-rpc-ql1.mschihuahua.org", "https://rpc.qom.one"],
  787: ["https://lb.routeme.sh/rpc/evm/787", "https://eth-rpc-acala.aca-staging.network", "https://rpc.evm.acala.network"],
  824: ["https://rpc.mainnet.dailycrypto.net", "https://rpc-2.mainnet.dailycrypto.net", "https://rpc-3.mainnet.dailycrypto.net"],
  841: ["https://rpc.mainnet.taraxa.io"],
  888: ["https://lb.routeme.sh/rpc/evm/888", "https://gwan-ssl.wandevs.org:56891", "https://gwan2-ssl.wandevs.org"],
  957: ["https://lb.routeme.sh/rpc/evm/957", "https://rpc.lyra.finance"],
  964: ["https://lb.routeme.sh/rpc/evm/964", "https://bittensor-lite-public.nodies.app", "https://rpc.blockmachine.io", "https://bittensor-finney.api.onfinality.io/public"],
  970: ["https://mainnet-rpc.oortech.com"],
  988: ["https://lb.routeme.sh/rpc/evm/988", "https://stable-mainnet.rpc.sentio.xyz", "https://stable.drpc.org"],
  995: ["https://lb.routeme.sh/rpc/evm/995", "https://rpc.5ire.network"],
  999: ["https://lb.routeme.sh/rpc/evm/999", "https://hyperevm.rpc.sentio.xyz", "https://rpc.nodeflare.app/hl/public", "https://gwan-ssl.wandevs.org:46891"],
  1012: ["https://lb.routeme.sh/rpc/evm/1012", "https://global.rpc.mainnet.newtonproject.org"],
  1030: ["https://lb.routeme.sh/rpc/evm/1030", "https://conflux-espace-public.unifra.io", "https://conflux-espace.blockpi.network/v1/rpc/public"],
  1088: ["https://lb.routeme.sh/rpc/evm/1088", "https://metis-public.nodies.app", "https://metis.drpc.org", "https://rpc.swiftnodes.io/rpc/metis", "https://metis-rpc.publicnode.com"],
  1100: ["https://lb.routeme.sh/rpc/evm/1100", "https://jsonrpc.dymension.nodestake.org", "https://rollapp.jrpc.cumulo.com.es", "https://dymension.liquify.com/json-rpc", "https://dymension-evm.kynraze.com", "https://dymension.drpc.org", "https://rpc.mainnet.dymension.aviaone.com", "https://evm.rpc.mainnet.dymension.aviaone.com"],
  1101: ["https://lb.routeme.sh/rpc/evm/1101", "https://rpc.polygon-zkevm.gateway.fm", "https://public.1rpc.io/polygon/zkevm", "https://polygon-zkevm-mainnet.public.blastapi.io", "https://polygon-zkevm.drpc.org", "https://polygon-zkevm-public.nodies.app", "https://endpoints.omniatech.io/v1/polygon-zkevm/mainnet/public", "https://node.histori.xyz/polygon-zkevm-mainnet/8ry9f6t9dct1se2hlagxnd9n2a"],
  1111: ["https://lb.routeme.sh/rpc/evm/1111", "https://api.wemix.com", "https://wemix.drpc.org"],
  1116: ["https://lb.routeme.sh/rpc/evm/1116", "https://public.1rpc.io/core", "https://rpc.ankr.com/core", "https://core.drpc.org", "https://api.zan.top/core-mainnet", "https://rpc-core.icecreamswap.com"],
  1122: ["https://rpc.luxeports.com", "https://erpc.luxeports.com"],
  1130: ["https://dmc.mydefichain.com/mainnet", "https://dmc01.mydefichain.com/mainnet"],
  1135: ["https://lb.routeme.sh/rpc/evm/1135", "https://lisk.drpc.org", "https://lisk.gateway.tenderly.co", "https://api-lisk-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c", "https://lisk-mainnet.gateway.tatum.io"],
  1215: ["https://mainnet.adftechnology.com"],
  1231: ["https://ultron-rpc.net"],
  1234: ["https://lb.routeme.sh/rpc/evm/1234", "https://rpc.step.network"],
  1284: ["https://lb.routeme.sh/rpc/evm/1284", "https://moonbeam.api.onfinality.io/public", "https://moonbeam.unitedbloc.com", "https://public.1rpc.io/glmr", "https://moonbeam-rpc.dwellir.com", "https://moonbeam.therpc.io", "https://endpoints.omniatech.io/v1/moonbeam/mainnet/public", "https://rpc.poolz.finance/moonbeam"],
  1285: ["https://lb.routeme.sh/rpc/evm/1285", "https://moonriver.api.onfinality.io/public", "https://moonriver.unitedbloc.com", "https://moonriver-rpc.dwellir.com", "https://moonriver-rpc.publicnode.com", "https://moonriver.drpc.org", "https://rpc.owlracle.info/movr/70d38ce1826c4a60bb2a8e05a6c8b20f", "https://moonriver.api.pocket.network"],
  1300: ["https://lb.routeme.sh/rpc/evm/1300", "https://rpc.glue.net"],
  1329: ["https://lb.routeme.sh/rpc/evm/1329", "https://sei.drpc.org", "https://sei-evm-rpc.stakeme.pro", "https://sei-public.nodies.app", "https://sei.therpc.io", "https://sei.api.pocket.network", "https://rpc.swiftnodes.io/rpc/sei", "https://evm-rpc-sei.stingray.plus"],
  1480: ["https://evm-rpc-vana.josephtran.xyz", "https://evm-rpc-vana.j-node.net", "https://islander-vana-rpc.spidernode.net"],
  1514: ["https://lb.routeme.sh/rpc/evm/1514", "https://mainnet.storyrpc.io", "https://story-evm-rpc.spidernode.net", "https://evm-rpc.story.mainnet.dteam.tech", "https://infra.originstake.com/story/evm", "https://lightnode-json-rpc-mainnet-story.grandvalleys.com", "https://story-mainnet-evm.itrocket.net", "https://evm-rpc-story.j-node.net"],
  1559: ["https://lb.routeme.sh/rpc/evm/1559", "https://rpc.ankr.com/tenet_evm", "https://tenet-evm.publicnode.com"],
  1597: ["https://mainnet-rpc.rnk.dev"],
  1612: ["https://rpc.openledger.xyz"],
  1625: ["https://lb.routeme.sh/rpc/evm/1625", "https://rpc.ankr.com/gravity"],
  1643: ["https://rpc.xgr.network", "https://rpc1.xgr.network", "https://rpc2.xgr.network"],
  1689: ["https://rpc.nerochain.io"],
  1729: ["https://lb.routeme.sh/rpc/evm/1729", "https://rpc.reya.network"],
  1750: ["https://lb.routeme.sh/rpc/evm/1750", "https://metall2.drpc.org"],
  1776: ["https://sentry.evm-rpc.injective.network", "https://injectiveevm-rpc.polkachu.com"],
  1868: ["https://lb.routeme.sh/rpc/evm/1868", "https://rpc.nodeflare.app/soneium/public", "https://soneium.drpc.org", "https://soneium-mainnet.rpc.sentio.xyz", "https://rpc.swiftnodes.io/rpc/soneium"],
  1875: ["https://lb.routeme.sh/rpc/evm/1875", "https://rpc.whitechain.io"],
  1890: ["https://lb.routeme.sh/rpc/evm/1890", "https://endpoints.omniatech.io/v1/lightlink/phoenix/public"],
  1919: ["https://rpc.turkscan.com"],
  1923: ["https://lb.routeme.sh/rpc/evm/1923", "https://swell-mainnet.rpc.sentio.xyz"],
  1983: ["https://mainnet1.krown.network"],
  1996: ["https://mainnet.sanko.xyz"],
  2000: ["https://lb.routeme.sh/rpc/evm/2000", "https://rpc-us.dogechain.dog", "https://rpc-sg.dogechain.dog", "https://rpc01-sg.dogechain.dog", "https://rpc02-sg.dogechain.dog", "https://rpc03-sg.dogechain.dog", "https://doge-mainnet.gateway.tatum.io", "https://rpc.ankr.com/dogechain"],
  2020: ["https://lb.routeme.sh/rpc/evm/2020", "https://ronin.drpc.org", "https://ronin-mainnet.gateway.tatum.io", "https://api-ronin-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c", "https://ronin.gateway.tenderly.co"],
  2021: ["https://mainnet2.edgewa.re/evm", "https://mainnet3.edgewa.re/evm", "https://edgeware-evm0.jelliedowl.net", "https://edgeware-evm1.jelliedowl.net", "https://edgeware-evm2.jelliedowl.net", "https://edgeware-evm3.jelliedowl.net", "https://edgeware.api.onfinality.io/public", "https://edgeware-evm.jelliedowl.net"],
  2026: ["https://rpc.edgeless.network/http"],
  2040: ["https://rpc.vanarchain.com"],
  2152: ["https://lb.routeme.sh/rpc/evm/2152", "https://rpc-mainnet.fra.tech", "https://rpc-mainnet.findora.org"],
  2184: ["https://api.popdex.xyz/api/v1/web3/rpc"],
  2187: ["https://mainnet-rpc.game7.build", "https://mainnet-rpc.game7.io"],
  2192: ["https://snaxchain.drpc.org"],
  2222: ["https://lb.routeme.sh/rpc/evm/2222", "https://kava.api.onfinality.io/public", "https://kava-evm-rpc.publicnode.com", "https://kava-public.nodies.app", "https://evm.kava.chainstacklabs.com", "https://rpc.ankr.com/kava_evm", "https://evm.kava-rpc.com", "https://kava.drpc.org"],
  2288: ["https://moca.drpc.org", "https://rpc.mocachain.dev"],
  2345: ["https://lb.routeme.sh/rpc/evm/2345", "https://rpc.goat.network", "https://goat-mainnet-alpha.drpc.org", "https://rpc.ankr.com/goat_mainnet"],
  2355: ["https://rpc.silicon.network", "https://silicon-mainnet.nodeinfra.com"],
  2525: ["https://lb.routeme.sh/rpc/evm/2525", "https://inevm.calderachain.xyz/http"],
  2741: ["https://lb.routeme.sh/rpc/evm/2741", "https://abstract.drpc.org", "https://abstract.api.onfinality.io/public", "https://abstract-mainnet.gateway.tatum.io"],
  2818: ["https://lb.routeme.sh/rpc/evm/2818", "https://rpc-quicknode.morphl2.io", "https://morph.drpc.org"],
  2882: ["https://node.chips.ooo/wasp/api/v1/chains/iota1pp3d3mnap3ufmgqnjsnw344sqmf5svjh26y2khnmc89sv6788y3r207a8fn/evm"],
  2911: ["https://rpc.hychain.com/http"],
  3068: ["https://lb.routeme.sh/rpc/evm/3068", "https://public-01.mainnet.bifrostnetwork.com/rpc", "https://public-02.mainnet.bifrostnetwork.com/rpc"],
  3109: ["https://alpha-rpc-node-http.svmscan.io"],
  3338: ["https://lb.routeme.sh/rpc/evm/3338", "https://peaq.api.onfinality.io/public"],
  3637: ["https://rpc.ankr.com/botanix_mainnet"],
  3721: ["https://rpc.xone.org", "https://rpc-node-1.xone.org", "https://rpc-node-2.xone.org", "https://rpc-node-3.xone.org", "https://rpc-node-4.xone.org"],
  3737: ["https://lb.routeme.sh/rpc/evm/3737", "https://rpc.crossbell.io"],
  3776: ["https://rpc.startale.com/astar-zkevm", "https://astar-zkevm-rpc.dwellir.com"],
  3888: ["https://lb.routeme.sh/rpc/evm/3888", "https://rpc.kalychain.io/rpc"],
  3946: ["https://mainnet.rpc.nexus.xyz"],
  4153: ["https://rpc.risechain.com"],
  4158: ["https://lb.routeme.sh/rpc/evm/4158", "https://rpc.mainnet.ms"],
  4200: ["https://lb.routeme.sh/rpc/evm/4200", "https://merlin.blockpi.network/v1/rpc/public", "https://rpc-merlin.rockx.com", "https://merlin-mainnet-enterprise.unifra.io", "https://endpoints.omniatech.io/v1/merlin/mainnet/public", "https://merlin.drpc.org"],
  4207: ["https://rpc.layeredge.io", "https://layeredge-mainnet-evm.itrocket.net", "https://layeredge.rpc.subquery.network/public", "https://rpc.layeredge.foundation"],
  4217: ["https://lb.routeme.sh/rpc/evm/4217", "https://rpc.mainnet.tempo.xyz"],
  4242: ["https://rpc.chain.nexi.technology", "https://chain.nexilix.com", "https://chain.nexi.evmnode.online"],
  4321: ["https://rpc-echos-mainnet-0.t.conduit.xyz"],
  4326: ["https://lb.routeme.sh/rpc/evm/4326", "https://rpc-megaeth-mainnet.globalstake.io", "https://megaeth.drpc.org", "https://megaeth.rpc.sentio.xyz"],
  4337: ["https://lb.routeme.sh/rpc/evm/4337", "https://build.onbeam.com/rpc", "https://subnets.avax.network/beam/mainnet/rpc"],
  4352: ["https://rpc.memecore.net"],
  4547: ["https://rpc.trumpchain.dev", "https://testnet.trumpchain.dev/http"],
  4663: ["https://robinhood.rpc.blxrbdn.com", "https://robinhood-rpc.publicnode.com", "https://robinhood.api.pocket.network", "https://lb.routeme.sh/rpc/evm/4663", "https://rpc.nodeflare.app/robinhood/public", "https://rpc-robinhood.blockmachine.io", "https://rpc.ordofi.network", "https://rpc.arrowrpc.com"],
  4689: ["https://lb.routeme.sh/rpc/evm/4689", "https://babel-api.mainnet.iotex.io", "https://babel-api.mainnet.iotex.one", "https://babel-api.fastblocks.io", "https://rpc.depinscan.io/iotex", "https://rpc.chainanalytics.org/iotex", "https://iotex-network.rpc.thirdweb.com", "https://iotex.api.onfinality.io/public"],
  4999: ["https://mainnet.blackfort.network/rpc", "https://mainnet-1.blackfort.network/rpc", "https://mainnet-2.blackfort.network/rpc", "https://mainnet-3.blackfort.network/rpc"],
  5000: ["https://lb.routeme.sh/rpc/evm/5000", "https://rpc.nodeflare.app/mantle/public", "https://mantle-mainnet.public.blastapi.io", "https://mantle-public.nodies.app", "https://mantle-rpc.publicnode.com", "https://mantle.drpc.org", "https://public.1rpc.io/mantle", "https://mantle.api.onfinality.io/public"],
  5031: ["https://somnia-rpc.publicnode.com"],
  5042: ["https://rpc.arc.io"],
  5112: ["https://rpc.ham.fun"],
  5165: ["https://lb.routeme.sh/rpc/evm/5165", "https://rpc1.bahamut.io", "https://rpc2.bahamut.io", "https://rpc1.ftnscan.io", "https://rpc2.ftnscan.io", "https://bahamut-rpc.publicnode.com", "https://Bahamut-mainnet-2h93.zeeve.net", "https://rpc.ankr.com/bahamut"],
  5234: ["https://lb.routeme.sh/rpc/evm/5234", "https://explorer-rpc-http.mainnet.stages.humanode.io"],
  5330: ["https://lb.routeme.sh/rpc/evm/5330", "https://superseed.drpc.org"],
  5424: ["https://rpc.edexa.network", "https://rpc.edexa.com"],
  5464: ["https://sagaevm.jsonrpc.sagarpc.io"],
  5545: ["https://rpc.duckchain.io", "https://rpc-hk.duckchain.io"],
  5551: ["https://l2.nahmii.io"],
  5845: ["https://lb.routeme.sh/rpc/evm/5845", "https://rpc.tangle.tools"],
  5858: ["https://rpc.cthscan.com"],
  6122: ["https://tea.drpc.org", "https://rpc.tea.xyz"],
  6969: ["https://lb.routeme.sh/rpc/evm/6969", "https://rpc.tombchain.com"],
  7000: ["https://lb.routeme.sh/rpc/evm/7000", "https://zetachain-mainnet.g.allthatnode.com/archive/evm", "https://zeta-chain.drpc.org", "https://zetachain-mainnet.public.blastapi.io", "https://7000.rpc.thirdweb.com", "https://api-zetachain-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  7070: ["https://planq-public.nodies.app", "https://jsonrpc.planq.nodestake.top", "https://evm-rpc.planq.network"],
  7119: ["https://rpc.sentrixchain.com"],
  7171: ["https://connect.bit-rock.io", "https://brockrpc.io"],
  7200: ["https://evm.exsat.network"],
  7233: ["https://rpc-mainnet.inichain.com"],
  7332: ["https://lb.routeme.sh/rpc/evm/7332", "https://rpc.ankr.com/horizen_eon"],
  7518: ["https://lb.routeme.sh/rpc/evm/7518", "https://rpc.meversemainnet.io"],
  7560: ["https://lb.routeme.sh/rpc/evm/7560", "https://rpc.cyber.co"],
  7667: ["https://rpc.carrchain.io"],
  7668: ["https://lb.routeme.sh/rpc/evm/7668", "https://root.rootnet.live/archive"],
  7700: ["https://lb.routeme.sh/rpc/evm/7700", "https://canto.evm.chandrastation.com", "https://jsonrpc.canto.nodestake.top", "https://canto.dexvaults.com", "https://canto-rpc.ansybl.io", "https://canto.dexrouting.com", "https://mainnode.plexnode.org:8545", "https://canto.slingshot.finance"],
  7887: ["https://rpc.ankr.com/kinto", "https://kinto-mainnet.calderachain.xyz/http"],
  7897: ["https://lb.routeme.sh/rpc/evm/7897", "https://rpc.arena-z.gg"],
  7979: ["https://lb.routeme.sh/rpc/evm/7979", "https://main.doschain.com"],
  8008: ["https://lb.routeme.sh/rpc/evm/8008"],
  8017: ["https://mainnet.isuncoin.com"],
  8118: ["https://api.shardeum.org"],
  8217: ["https://lb.routeme.sh/rpc/evm/8217", "https://alpha-hardworking-orb.kaia-mainnet.quiknode.pro", "https://kaia.api.pocket.network", "https://kaia-public.nodies.app", "https://go.getblock.io/d7094dbd80ab474ba7042603fe912332", "https://klaytn.api.onfinality.io/public", "https://public.1rpc.io/klay", "https://klaytn.drpc.org"],
  8333: ["https://lb.routeme.sh/rpc/evm/8333", "https://mainnet-rpc.b3.fun"],
  8428: ["https://api.thatchain.io", "https://api.thatchain.io/mainnet"],
  8453: ["https://lb.routeme.sh/rpc/evm/8453", "https://rpc.nodeflare.app/base/public", "https://developer-access-mainnet.base.org", "https://li-fi-base.intustechno.workers.dev/rpc", "https://base-mainnet.diamondswap.org/rpc", "https://base.public.blockpi.network/v1/rpc/public", "https://public.1rpc.io/base", "https://base-public.nodies.app"],
  8668: ["https://lb.routeme.sh/rpc/evm/8668", "https://mainnet-rpc.helachain.com"],
  8765: ["https://evm.wardenprotocol.org"],
  8822: ["https://lb.routeme.sh/rpc/evm/8822", "https://json-rpc.evm.iotaledger.net", "https://iota-mainnet-evm.public.blastapi.io", "https://rpc.ankr.com/iota_evm", "https://iota-mainnet.gateway.tatum.io"],
  8853: ["https://rpc.myclique.io"],
  8866: ["https://mainnet.lumio.io"],
  8880: ["https://lb.routeme.sh/rpc/evm/8880", "https://rpc.unique.network", "https://eu-rpc.unique.network", "https://asia-rpc.unique.network", "https://us-rpc.unique.network"],
  8881: ["https://rpc-quartz.unique.network", "https://quartz.api.onfinality.io/public-ws", "https://eu-rpc-quartz.unique.network", "https://asia-rpc-quartz.unique.network", "https://us-rpc-quartz.unique.network"],
  8899: ["https://lb.routeme.sh/rpc/evm/8899", "https://rpc-l1.jibchain.net", "https://rpc-l1.inan.in.th"],
  9001: ["https://lb.routeme.sh/rpc/evm/9001", "https://evmos.lava.build", "https://evmos-mainnet.public.blastapi.io", "https://evmos-evm-rpc.publicnode.com", "https://jsonrpc-evmos.goldenratiostaking.net", "https://evmos-jsonrpc.cyphercore.io", "https://evmos.drpc.org", "https://jsonrpc-evmos-ia.cosmosia.notional.ventures"],
  9700: ["https://dev-rpc.oortech.com"],
  9745: ["https://lb.routeme.sh/rpc/evm/9745", "https://rpc.nodeflare.app/plasma/public", "https://plasma.drpc.org", "https://plasma.api.onfinality.io/public", "https://rpc.swiftnodes.io/rpc/plasma", "https://plasma-mainnet.gateway.tatum.io"],
  9790: ["https://lb.routeme.sh/rpc/evm/9790", "https://evm-api.carbon.network"],
  10000: ["https://lb.routeme.sh/rpc/evm/10000", "https://smartbch.fountainhead.cash/mainnet", "https://global.uat.cash", "https://rpc.uatvo.com", "https://bch-mainnet.gateway.tatum.io", "https://smartbch.greyh.at", "https://rpc.smartbch.org", "https://rpc-mainnet.smartbch.org"],
  10242: ["https://rpc.arthera.net"],
  11100: ["https://beta-rpc-node-http.bool.network"],
  11235: ["https://lb.routeme.sh/rpc/evm/11235", "https://rpc.eth.haqq.network", "https://haqq-evm.publicnode.com", "https://evm.haqq.sh", "https://haqq-mainnet.gateway.tatum.io", "https://haqq.drpc.org", "https://haqq-evm-rpc.publicnode.com"],
  11501: ["https://lb.routeme.sh/rpc/evm/11501", "https://rpc-mainnet-1.geb.network", "https://rpc-mainnet-2.geb.network"],
  11820: ["https://node-euro.artela.network/rpc", "https://node-hongkong.artela.network/rpc"],
  12306: ["https://lb.routeme.sh/rpc/evm/12306", "https://node1.fibo-api.asia", "https://node2.fibo-api.asia", "https://node3.fibo-api.asia", "https://node4.fibo-api.asia", "https://node5.fibo-api.asia", "https://node6.fibo-api.asia", "https://node7.fibo-api.asia"],
  12323: ["https://huddle01.calderachain.xyz/http"],
  12324: ["https://rpc-mainnet.l3x.com"],
  12553: ["https://lb.routeme.sh/rpc/evm/12553", "https://rpc.rss3.io"],
  13371: ["https://lb.routeme.sh/rpc/evm/13371", "https://immutable-zkevm.drpc.org", "https://immutable.gateway.tenderly.co"],
  13381: ["https://rpc.phoenixplorer.com"],
  15551: ["https://api.mainnetloop.com"],
  16507: ["https://rpc.genesys.network"],
  16661: ["https://0g.drpc.org"],
  17777: ["https://lb.routeme.sh/rpc/evm/17777", "https://api.evm.eosnetwork.com", "https://eos-mainnet.gateway.tatum.io"],
  19991: ["https://evm.ultra.eosusa.io"],
  21000: ["https://api-hyperlane.nodes.torus.network", "https://api.torus.network", "https://rpc.actionblockchain.org"],
  22222: ["https://api.nautilus.nautchain.xyz"],
  22776: ["https://lb.routeme.sh/rpc/evm/22776", "https://rpc.maplabs.io"],
  23294: ["https://lb.routeme.sh/rpc/evm/23294", "https://sapphire.oasis.io", "https://public.1rpc.io/oasis/sapphire"],
  23451: ["https://rpc.dreyerx.com"],
  24101: ["https://rpc-archive.incentiv.io"],
  25327: ["https://everclear.drpc.org", "https://rpc.everclear.raas.gelato.cloud"],
  29548: ["https://lb.routeme.sh/rpc/evm/29548", "https://rpc.oasys.mycryptoheroes.net"],
  31337: ["https://testnet-rpc.gochain.io"],
  31612: ["https://lb.routeme.sh/rpc/evm/31612", "https://mezo.drpc.org", "https://rpc_evm-mezo.imperator.co", "https://mezo-mainnet.boar.network", "https://mainnet.mezo.public.validationcloud.io", "https://rpc-internal.mezo.org"],
  32520: ["https://rpc-bitgert.icecreamswap.com", "https://nodes.vefinetwork.org/bitgert", "https://flux-rpc.brisescan.com", "https://flux-rpc1.brisescan.com", "https://flux-rpc2.brisescan.com", "https://rpc-1.chainrpc.com", "https://rpc-2.chainrpc.com", "https://node1.serverrpc.com"],
  32659: ["https://mainnet.fusionnetwork.io"],
  32769: ["https://lb.routeme.sh/rpc/evm/32769", "https://api.zilliqa.com"],
  33139: ["https://lb.routeme.sh/rpc/evm/33139", "https://rpc.apechain.com", "https://apechain.drpc.org"],
  33979: ["https://lb.routeme.sh/rpc/evm/33979"],
  34443: ["https://lb.routeme.sh/rpc/evm/34443", "https://rpc.nodeflare.app/mode/public", "https://public.1rpc.io/mode", "https://mode.drpc.org", "https://mode.gateway.tenderly.co", "https://mode-mainnet.rpc.sentio.xyz"],
  35441: ["https://lb.routeme.sh/rpc/evm/35441", "https://rpc.q.org"],
  36900: ["https://adi.drpc.org"],
  41443: ["https://erpc.nesa.ai"],
  41444: ["https://erpc.ns.onyxpro.ai"],
  41455: ["https://lb.routeme.sh/rpc/evm/41455", "https://alephzero.drpc.org"],
  41923: ["https://lb.routeme.sh/rpc/evm/41923", "https://rpc.edu-chain.raas.gelato.cloud"],
  42026: ["https://rpc.donatuz.com"],
  42161: ["https://lb.routeme.sh/rpc/evm/42161", "https://rpc.nodeflare.app/arb/public", "https://public.1rpc.io/arb", "https://rpc.ankr.com/arbitrum/c4cc6a8c87ec30258076de433ab2cf3d834228aae3fc4d76087873e4fea11635", "https://arbitrum-one-public.nodies.app", "https://arb-mainnet.g.alchemy.com/v2/demo", "https://arbitrum-one.public.blastapi.io", "https://arb-mainnet-public.unifra.io"],
  42170: ["https://lb.routeme.sh/rpc/evm/42170", "https://rpc.nodeflare.app/nova/public", "https://arbitrum-nova.public.blastapi.io", "https://arbitrum-nova-rpc.publicnode.com", "https://arbitrum-nova.drpc.org", "https://arb-nova-mainnet.gateway.tatum.io", "https://arbitrum-nova.gateway.tenderly.co", "https://docs-demo.nova-mainnet.quiknode.pro"],
  42220: ["https://lb.routeme.sh/rpc/evm/42220", "https://rpc.celocolombia.org", "https://rpc.ankr.com/celo", "https://celo-mainnet.gateway.tatum.io", "https://celo.drpc.org", "https://celo-json-rpc.stakely.io", "https://celo.api.onfinality.io/public", "https://api-celo-mainnet-archive.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  42420: ["https://lb.routeme.sh/rpc/evm/42420", "https://mainnet-rpc.assetchain.org", "https://eth.nodebridge.xyz/assetchain/exec/b2da3d33-5708-4f61-8d1e-2c677124c35a"],
  42766: ["https://lb.routeme.sh/rpc/evm/42766", "https://rpc.zkfair.io", "https://endpoints.omniatech.io/v1/zkfair/mainnet/public"],
  42793: ["https://lb.routeme.sh/rpc/evm/42793", "https://node.mainnet.etherlink.com", "https://rpc.ankr.com/etherlink_mainnet"],
  43111: ["https://lb.routeme.sh/rpc/evm/43111", "https://hemi.drpc.org"],
  43114: ["https://lb.routeme.sh/rpc/evm/43114", "https://rpc.nodeflare.app/avax/public", "https://avalanche.public-rpc.com", "https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc", "https://avalancheapi.terminet.io/ext/bc/C/rpc", "https://public.1rpc.io/avax/c", "https://avalanche-public.nodies.app/ext/bc/C/rpc", "https://avalanche.api.onfinality.io/public/ext/bc/C/rpc"],
  43419: ["https://lb.routeme.sh/rpc/evm/43419", "https://rpc.gunzchain.io/ext/bc/2M47TxWHGnhNtq6pM5zPXdATBtuqubxn5EPFgFmEawCQr9WFML/rpc"],
  45003: ["https://rpc.juneo-mainnet.network/ext/bc/JUNE/rpc"],
  45004: ["https://rpc.juneo-mainnet.network/ext/bc/DAI1/rpc"],
  45005: ["https://rpc.juneo-mainnet.network/ext/bc/USDT1/rpc"],
  45006: ["https://rpc.juneo-mainnet.network/ext/bc/USD1/rpc"],
  45007: ["https://rpc.juneo-mainnet.network/ext/bc/mBTC1/rpc"],
  45008: ["https://rpc.juneo-mainnet.network/ext/bc/GLD1/rpc"],
  45009: ["https://rpc.juneo-mainnet.network/ext/bc/LTC1/rpc"],
  45010: ["https://rpc.juneo-mainnet.network/ext/bc/DOGE1/rpc"],
  45011: ["https://rpc.juneo-mainnet.network/ext/bc/EUR1/rpc"],
  45012: ["https://rpc.juneo-mainnet.network/ext/bc/SGD1/rpc"],
  45013: ["https://rpc.juneo-mainnet.network/ext/bc/BCH1/rpc"],
  45014: ["https://rpc.juneo-mainnet.network/ext/bc/LINK1/rpc"],
  47763: ["https://lb.routeme.sh/rpc/evm/47763", "https://mainnet-1.rpc.banelabs.org", "https://mainnet-2.rpc.banelabs.org"],
  47805: ["https://lb.routeme.sh/rpc/evm/47805", "https://rpc.rei.network"],
  48900: ["https://lb.routeme.sh/rpc/evm/48900", "https://rpc.nodeflare.app/zircuit/public", "https://zircuit1-mainnet.liquify.com", "https://zircuit.rpc.sentio.xyz", "https://zircuit1-mainnet.p2pify.com", "https://zircuit-mainnet.drpc.org"],
  50005: ["https://lb.routeme.sh/rpc/evm/50005", "https://rpc.yooldo-verse.xyz"],
  50104: ["https://lb.routeme.sh/rpc/evm/50104", "https://rpc-quicknode.sophon.xyz", "https://sophon-mainnet-public.unifra.io"],
  50342: ["https://mainnet.reddio.com/rpc"],
  52014: ["https://lb.routeme.sh/rpc/evm/52014", "https://rpc.ankr.com/electroneum"],
  52924: ["https://mainnet.lazai.network"],
  53456: ["https://rpc.birdlayer.xyz", "https://rpc1.birdlayer.xyz"],
  53935: ["https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc", "https://avax-dfk.api.pocket.network"],
  55244: ["https://lb.routeme.sh/rpc/evm/55244"],
  56288: ["https://lb.routeme.sh/rpc/evm/56288", "https://bnb.boba.network", "https://replica.bnb.boba.network", "https://boba-bnb.gateway.tenderly.co", "https://gateway.tenderly.co/public/boba-bnb", "https://boba-bnb.drpc.org"],
  57073: ["https://lb.routeme.sh/rpc/evm/57073", "https://rpc.nodeflare.app/ink/public", "https://ink.drpc.org", "https://ink-public.nodies.app", "https://ink.api.pocket.network"],
  59144: ["https://lb.routeme.sh/rpc/evm/59144", "https://rpc.nodeflare.app/linea/public", "https://public.1rpc.io/linea", "https://linea.drpc.org", "https://linea.decubate.com", "https://rpc.owlracle.info/linea/70d38ce1826c4a60bb2a8e05a6c8b20f", "https://linea.therpc.io", "https://linea.api.pocket.network"],
  60603: ["https://rpc.potos.hk"],
  60808: ["https://lb.routeme.sh/rpc/evm/60808", "https://rpc.nodeflare.app/bob/public", "https://bob.drpc.org", "https://bob.gateway.tenderly.co", "https://bob.rpc.sentio.xyz", "https://bob-mainnet.public.blastapi.io"],
  62050: ["https://lb.routeme.sh/rpc/evm/62050", "https://rpc-mainnet.optopia.ai", "https://rpc-mainnet-2.optopia.ai"],
  62606: ["https://mainnet-rpc.apolloscan.io"],
  63157: ["https://geist-mainnet.g.alchemy.com/public"],
  68414: ["https://henesys-rpc.msu.io"],
  70700: ["https://lb.routeme.sh/rpc/evm/70700", "https://rpc.apex.proofofplay.com"],
  71402: ["https://lb.routeme.sh/rpc/evm/71402", "https://v1.mainnet.godwoken.io/rpc"],
  73115: ["https://lb.routeme.sh/rpc/evm/73115", "https://rpc1-mainnet.icbnetwork.info", "https://rpc2-mainnet.icbnetwork.info", "https://main1.rpc-icb-network.io", "https://main2.rpc-icb-network.io", "https://mahour.icbnetwork.info"],
  80094: ["https://lb.routeme.sh/rpc/evm/80094", "https://berachain-rpc.publicnode.com", "https://berachain.drpc.org", "https://rpc.berachain-apis.com", "https://berachain.therpc.io", "https://berachain-mainnet.gateway.tatum.io", "https://bera.api.pocket.network", "https://api-berachain-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  80931: ["https://rpc-forta-chain-8gj1qndmfc.t.conduit.xyz"],
  81224: ["https://lb.routeme.sh/rpc/evm/81224", "https://rpc.codex.xyz"],
  81457: ["https://lb.routeme.sh/rpc/evm/81457", "https://blast.din.dev/rpc", "https://blastl2-mainnet.public.blastapi.io", "https://li-fi-blast.intustechno.workers.dev/rpc", "https://rpc.ankr.com/blast", "https://blast.gasswap.org", "https://blast-rpc.publicnode.com", "https://blast.drpc.org"],
  86608: ["https://rpc.cpchain.com"],
  88811: ["https://rpc.unit0.dev"],
  88888: ["https://lb.routeme.sh/rpc/evm/88888", "https://rpc.ankr.com/chiliz", "https://chiliz-mainnet.gateway.tatum.io", "https://api-chiliz-mainnet-archive.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c", "https://rpc.swiftnodes.io/rpc/chiliz", "https://chiliz.publicnode.com"],
  92278: ["https://lb.routeme.sh/rpc/evm/92278", "https://rpc.miracleplay.io"],
  96370: ["https://rpc.lumoz.org", "https://rpc-hk.lumoz.org"],
  97453: ["https://node.sidrachain.com"],
  98866: ["https://lb.routeme.sh/rpc/evm/98866", "https://plume.drpc.org", "https://plume-mainnet.gateway.tatum.io"],
  98881: ["https://rpc.ebi.xyz"],
  100009: ["https://rpc-mainnet.vechain.energy"],
  102030: ["https://creditcoin.drpc.org", "https://mainnet3.creditcoin.network"],
  105105: ["https://lb.routeme.sh/rpc/evm/105105", "https://rpc.xertra.com"],
  110110: ["https://lb.routeme.sh/rpc/evm/110110", "https://rpc.marscredit.xyz", "https://rpc.marscredit.xyz:443"],
  111188: ["https://lb.routeme.sh/rpc/evm/111188", "https://tangible-real.gateway.tenderly.co", "https://real.drpc.org"],
  124816: ["https://rpc.mitosis.org"],
  127001: ["https://mainnet-rpc.gravity.xyz"],
  167000: ["https://lb.routeme.sh/rpc/evm/167000", "https://rpc.taiko.xyz", "https://rpc.ankr.com/taiko", "https://rpc.taiko.tools", "https://taiko-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f", "https://taiko.drpc.org", "https://taiko-mainnet.rpc.porters.xyz/taiko-public", "https://taiko-mainnet.gateway.tenderly.co"],
  175200: ["https://lb.routeme.sh/rpc/evm/175200", "https://lit-chain-rpc.litprotocol.com"],
  190415: ["https://lb.routeme.sh/rpc/evm/190415", "https://mainnet.hpp.io"],
  200901: ["https://lb.routeme.sh/rpc/evm/200901", "https://rpc.ankr.com/bitlayer", "https://rpc.bitlayer-rpc.com", "https://rpc-bitlayer.rockx.com"],
  309075: ["https://lb.routeme.sh/rpc/evm/309075", "https://mainnet-rpc.oneworldchain.org"],
  360890: ["https://lb.routeme.sh/rpc/evm/360890", "https://tsub360890-eth-rpc.thetatoken.org/rpc"],
  383353: ["https://rpc.cheesechain.xyz", "https://rpc.cheesechain.xyz/http", "https://cheesechain.calderachain.xyz/http"],
  440017: ["https://anon-entrypoint-1.atgraphite.com"],
  513100: ["https://rpc.etherfair.org"],
  534352: ["https://lb.routeme.sh/rpc/evm/534352", "https://rpc-scroll.icecreamswap.com", "https://scroll-mainnet.public.blastapi.io", "https://scroll-mainnet-public.unifra.io", "https://public.1rpc.io/scroll", "https://scroll.drpc.org", "https://scroll.api.pocket.network", "https://scroll.api.onfinality.io/public"],
  543210: ["https://lb.routeme.sh/rpc/evm/543210", "https://zero.drpc.org"],
  555888: ["https://dustboy-rpc.jibl2.com"],
  613419: ["https://galactica-mainnet.g.alchemy.com/public"],
  641230: ["https://lb.routeme.sh/rpc/evm/641230", "https://brnkc-mainnet.bearnetwork.net", "https://brnkc-mainnet1.bearnetwork.net"],
  660279: ["https://lb.routeme.sh/rpc/evm/660279", "https://rpc.ankr.com/xai"],
  668668: ["https://conwai.calderachain.xyz/http"],
  685689: ["https://gensyn-mainnet.g.alchemy.com/public"],
  723487: ["https://rpc.radiustech.xyz"],
  747474: ["https://lb.routeme.sh/rpc/evm/747474", "https://katana.drpc.org", "https://rpc.swiftnodes.io/rpc/katana", "https://katana.rpc.sentio.xyz", "https://katana.gateway.tenderly.co", "https://rpc.katanarpc.com"],
  752025: ["https://rpc-mainnet.zkevm.ternoa.network"],
  810180: ["https://lb.routeme.sh/rpc/evm/810180"],
  888888: ["https://lb.routeme.sh/rpc/evm/888888", "https://infragrid.v.network/ethereum/compatible"],
  984122: ["https://lb.routeme.sh/rpc/evm/984122"],
  1032009: ["https://rpc.infinityvm.xyz"],
  1440000: ["https://xrplevm.buildintheshade.com", "https://xrpl.drpc.org"],
  2632500: ["https://lb.routeme.sh/rpc/evm/2632500", "https://coti-rpc.Hyperflow.finance", "https://rpc.poolz.finance/coti", "https://tokyo.fullnode.mainnet.coti.io/rpc", "https://virginia.fullnode.mainnet.coti.io/rpc", "https://new-york.fullnode.mainnet.coti.io/rpc", "https://community-enabler-1.fullnode.mainnet.coti.io/rpc", "https://mainnet.innovunode.io/rpc"],
  4278608: ["https://arcadia.khalani.network"],
  5734951: ["https://jovay.drpc.org", "https://rpc.jovay.io"],
  6985385: ["https://humanity-mainnet.g.alchemy.com/public"],
  7771777: ["https://rpc-gw-1.vyoscan.com/ext/bc/2t51dXsuxUvd9teY9TKEJmgxmxMk3CRF88UYTA4HQgjeYZqzSX/rpc", "https://rpc-gw-2.vyoscan.com/ext/bc/2t51dXsuxUvd9teY9TKEJmgxmxMk3CRF88UYTA4HQgjeYZqzSX/rpc"],
  7773777: ["https://rpc-gw-1.vyoscan.com/ext/bc/2RyzsmGypNQZPby1miwMMV8spTvhgd9qd2peNRzU1mErUQqSSw/rpc", "https://rpc-gw-2.vyoscan.com/ext/bc/2RyzsmGypNQZPby1miwMMV8spTvhgd9qd2peNRzU1mErUQqSSw/rpc"],
  7777777: ["https://lb.routeme.sh/rpc/evm/7777777", "https://zora.drpc.org", "https://api-zora-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  9999999: ["https://rpc.mainnet.fluence.dev"],
  10241024: ["https://lb.routeme.sh/rpc/evm/10241024", "https://rpc.alienxchain.io/http"],
  19880818: ["https://lb.routeme.sh/rpc/evm/19880818", "https://rpc.dbcwallet.io"],
  20240603: ["https://lb.routeme.sh/rpc/evm/20240603", "https://rpc.mainnet.dbkchain.io"],
  20250217: ["https://lb.routeme.sh/rpc/evm/20250217", "https://rpc.ankr.com/xphere_mainnet", "https://en-bkk.x-phere.com"],
  20256789: ["https://rpc.etpscan.xyz"],
  21000000: ["https://lb.routeme.sh/rpc/evm/21000000", "https://mainnet.corn-rpc.com", "https://rpc.ankr.com/corn_maizenet", "https://maizenet-rpc.usecorn.com"],
  22052002: ["https://lb.routeme.sh/rpc/evm/22052002", "https://edgewallet1.xlon.org"],
  245022934: ["https://lb.routeme.sh/rpc/evm/245022934", "https://neon-proxy-mainnet.solana.p2p.org", "https://neon-mainnet.everstake.one", "https://neon-evm.drpc.org"],
  253368190: ["https://rpc.flame.astria.org"],
  278611351: ["https://mainnet.skalenodes.com/v1/turbulent-unique-scheat"],
  333000333: ["https://rpc-1.meld.com"],
  666666666: ["https://lb.routeme.sh/rpc/evm/666666666"],
  728126428: ["https://lb.routeme.sh/rpc/evm/728126428", "https://tron.drpc.org", "https://tron.therpc.io/jsonrpc", "https://tron.api.pocket.network", "https://tron-mainnet.gateway.tatum.io", "https://tron.rpc.sentio.xyz", "https://rpc.ankr.com/tron_jsonrpc"],
  888888888: ["https://lb.routeme.sh/rpc/evm/888888888"],
  994873017: ["https://lb.routeme.sh/rpc/evm/994873017"],
  1273227453: ["https://lb.routeme.sh/rpc/evm/1273227453", "https://mainnet.skalenodes.com/v1/wan-red-ain"],
  1313161554: ["https://lb.routeme.sh/rpc/evm/1313161554", "https://public.1rpc.io/aurora", "https://aurora.drpc.org", "https://aurora-mainnet.gateway.tatum.io", "https://endpoints.omniatech.io/v1/aurora/mainnet/public", "https://rpc.owlracle.info/aurora/70d38ce1826c4a60bb2a8e05a6c8b20f"],
  1350216234: ["https://lb.routeme.sh/rpc/evm/1350216234", "https://mainnet.skalenodes.com/v1/parallel-stormy-spica"],
  1380012617: ["https://lb.routeme.sh/rpc/evm/1380012617", "https://mainnet.rpc.rarichain.org/http", "https://rari.calderachain.xyz/http"],
  1482601649: ["https://lb.routeme.sh/rpc/evm/1482601649", "https://mainnet.skalenodes.com/v1/green-giddy-denebola"],
  1564830818: ["https://lb.routeme.sh/rpc/evm/1564830818", "https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague"],
  1666600000: ["https://lb.routeme.sh/rpc/evm/1666600000", "https://api.harmony.one", "https://a.api.s0.t.hmny.io", "https://api.s0.t.hmny.io", "https://public.1rpc.io/one", "https://endpoints.omniatech.io/v1/harmony/mainnet-0/public", "https://harmony-0.drpc.org", "https://rpc.owlracle.info/one/70d38ce1826c4a60bb2a8e05a6c8b20f"],
  2046399126: ["https://lb.routeme.sh/rpc/evm/2046399126", "https://mainnet.skalenodes.com/v1/elated-tan-skat"],
  11297108109: ["https://lb.routeme.sh/rpc/evm/11297108109", "https://palm-mainnet.infura.io/v3/3a961d6501e54add9a41aa53f15de99b", "https://palm-mainnet.public.blastapi.io", "https://palm-mainnet.gateway.tatum.io"],
  383414847825: ["https://api.zeniq.network"],
  2716446429837000: ["https://lb.routeme.sh/rpc/evm/2716446429837000", "https://dchain-2716446429837000-1.jsonrpc.sagarpc.io"],
};
