/**
 * Extra public endpoints per chain, tried after the one viem carries.
 *
 * GENERATED FILE. Do not edit by hand: run \`npm run sync:rpcs\`.
 *
 * viem lists a single endpoint per chain. That is enough for the majors and
 * not enough for the long tail, where one refusal takes the whole chain out
 * of the report - and a missing chain reads as "no liquidity here", which is
 * the opposite of what it means.
 *
 * Source: chainlist-rpcs@0.5.310, the data behind chainlist.org.
 */
export const EXTRA_RPC_URLS: Record<string, string[]> = {
  "ethereum": ["https://lb.routeme.sh/rpc/evm/1", "https://one.valve.city/rpc/vk_demo/evm/1", "https://rpc.nodeflare.app/eth/public", "https://go.getblock.io/aefd01aa907c4805ba3c00a9e5b48c6b"],
  "optimism": ["https://lb.routeme.sh/rpc/evm/10", "https://rpc.nodeflare.app/op/public", "https://mainnet.optimism.io/", "https://optimism-mainnet.public.blastapi.io"],
  "flare": ["https://lb.routeme.sh/rpc/evm/14", "https://flare-mainnet.gateway.tatum.io/", "https://flare.drpc.org"],
  "cronos": ["https://lb.routeme.sh/rpc/evm/25", "https://rpc.nodeflare.app/cronos/public", "https://cronos-rpc.elk.finance/", "https://cronos-evm-rpc.publicnode.com"],
  "deprecatedrootstock": ["https://lb.routeme.sh/rpc/evm/30", "https://mycrypto.rsk.co", "https://rootstock.drpc.org", "https://rootstock-mainnet.public.blastapi.io"],
  "xpla": ["https://lb.routeme.sh/rpc/evm/37"],
  "telos": ["https://lb.routeme.sh/rpc/evm/40", "https://public.1rpc.io/telos/evm", "https://telos.drpc.org", "https://rpc.ankr.com/telos"],
  "lukso": ["https://lb.routeme.sh/rpc/evm/42", "https://rpc.lukso.sigmacore.io", "https://42.rpc.thirdweb.com", "https://public-lukso.nownodes.io"],
  "bsc": ["https://lb.routeme.sh/rpc/evm/56", "https://rpc.nodeflare.app/bnb/public", "https://bsc-dataseed.bnbchain.org/", "https://bsc.campioneinfrastructure.com"],
  "syscoin": ["https://lb.routeme.sh/rpc/evm/57", "https://rpc.ankr.com/syscoin", "https://syscoin-evm.publicnode.com"],
  "viction": ["https://viction.drpc.org", "https://lb.routeme.sh/rpc/evm/88"],
  "gnosis": ["https://lb.routeme.sh/rpc/evm/100", "https://xdai-archive.blockscout.com", "https://gnosis-public.nodies.app", "https://rpc.gnosis.gateway.fm"],
  "shibarium": ["https://shibarium.drpc.org"],
  "fusemainnet": ["https://lb.routeme.sh/rpc/evm/122", "https://fuse-public.nodies.app", "https://fuse-mainnet.chainstacklabs.com", "https://fuse.api.onfinality.io/public"],
  "unichain": ["https://lb.routeme.sh/rpc/evm/130", "https://rpc.nodeflare.app/unichain/public", "https://mainnet.unichain.org/", "https://unichain.api.onfinality.io/public"],
  "polygon": ["https://lb.routeme.sh/rpc/evm/137", "https://rpc.nodeflare.app/polygon/public", "https://rpc-mainnet.matic.quiknode.pro", "https://polygon-public.nodies.app"],
  "monad": ["https://lb.routeme.sh/rpc/evm/143", "https://monad-mainnet.api.onfinality.io/public", "https://monad-mainnet.drpc.org", "https://monad-mainnet-rpc.spidernode.net/"],
  "sonic": ["https://lb.routeme.sh/rpc/evm/146", "https://rpc.nodeflare.app/sonic/public", "https://sonic.drpc.org", "https://rpc.ankr.com/sonic_mainnet"],
  "mantapacific": ["https://lb.routeme.sh/rpc/evm/169", "https://public.1rpc.io/manta", "https://manta-pacific-gascap.calderachain.xyz/http", "https://www.tencentcloud-rpc.com/v2/manta/manta-rpc"],
  "hashkey": ["https://hashkey.drpc.org"],
  "xlayer": ["https://lb.routeme.sh/rpc/evm/196", "https://rpc.nodeflare.app/xlayer/public", "https://rpc.xlayer.tech", "https://endpoints.omniatech.io/v1/xlayer/mainnet/public"],
  "opbnb": ["https://lb.routeme.sh/rpc/evm/204", "https://opbnb.drpc.org", "https://opbnb-rpc.publicnode.com", "https://public.1rpc.io/opbnb"],
  "bsquared": ["https://lb.routeme.sh/rpc/evm/223", "https://b2-mainnet.alt.technology", "https://b2-mainnet-public.s.chainbase.com", "https://mainnet.b2-rpc.com"],
  "lens": ["https://lb.routeme.sh/rpc/evm/232", "https://light-icy-dinghy.lens-mainnet.quiknode.pro", "https://lens-mainnet.g.alchemy.com/public", "https://lens.drpc.org"],
  "tac": ["https://lb.routeme.sh/rpc/evm/239", "https://tac.therpc.io", "https://tac.drpc.org"],
  "fantom": ["https://lb.routeme.sh/rpc/evm/250", "https://rpcapi.fantom.network", "https://fantom-public.nodies.app", "https://rpc.ftm.tools/"],
  "fraxtal": ["https://lb.routeme.sh/rpc/evm/252", "https://fraxtal.drpc.org", "https://fraxtal.gateway.tenderly.co", "https://node.histori.xyz/fraxtal-mainnet/8ry9f6t9dct1se2hlagxnd9n2a"],
  "kroma": ["https://lb.routeme.sh/rpc/evm/255", "https://kroma.drpc.org", "https://rpc-kroma.rockx.com"],
  "boba": ["https://lb.routeme.sh/rpc/evm/288", "https://mainnet.boba.network/", "https://boba-ethereum.gateway.tenderly.co", "https://gateway.tenderly.co/public/boba-ethereum"],
  "orderly": ["https://lb.routeme.sh/rpc/evm/291", "https://orderly.drpc.org"],
  "filecoin": ["https://lb.routeme.sh/rpc/evm/314", "https://api.node.glif.io", "https://node.filutils.com/rpc/v1", "https://rpc.ankr.com/filecoin"],
  "zksync": ["https://lb.routeme.sh/rpc/evm/324", "https://li-fi-redirect.intustechno.workers.dev/rpc", "https://go.getblock.io/f76c09905def4618a34946bf71851542", "https://zksync.meowrpc.com"],
  "molten": ["https://lb.routeme.sh/rpc/evm/360", "https://shape-mainnet.g.alchemy.com/public"],
  "pulsechain": ["https://lb.routeme.sh/rpc/evm/369", "https://rpc.gigatheminter.com", "https://rpc-pulsechain.g4mm4.io", "https://evex.cloud/pulserpc"],
  "cronoszkevm": ["https://lb.routeme.sh/rpc/evm/388", "https://cronos-zkevm.drpc.org", "https://cronos-zkevm.rpc.sentio.xyz"],
  "worldchain": ["https://lb.routeme.sh/rpc/evm/480", "https://480.rpc.thirdweb.com", "https://worldchain-mainnet.gateway.tenderly.co", "https://sparkling-autumn-dinghy.worldchain-mainnet.quiknode.pro"],
  "astar": ["https://lb.routeme.sh/rpc/evm/592", "https://evm.astar.network/", "https://rpc.astar.network:8545", "https://astar.public.blastapi.io"],
  "redstone": ["https://lb.routeme.sh/rpc/evm/690"],
  "matchain": ["https://lb.routeme.sh/rpc/evm/698", "https://rpc.ankr.com/matchain_mainnet"],
  "deprecatedflow": ["https://lb.routeme.sh/rpc/evm/747", "https://flow-mainnet.gateway.tatum.io/"],
  "acala": ["https://lb.routeme.sh/rpc/evm/787", "https://eth-rpc-acala.aca-staging.network", "https://rpc.evm.acala.network"],
  "subtensor": ["https://lb.routeme.sh/rpc/evm/964", "https://bittensor-lite-public.nodies.app", "https://rpc.blockmachine.io"],
  "stable": ["https://lb.routeme.sh/rpc/evm/988", "https://stable-mainnet.rpc.sentio.xyz", "https://stable.drpc.org"],
  "hyperevm": ["https://lb.routeme.sh/rpc/evm/999", "https://hyperevm.rpc.sentio.xyz", "https://rpc.nodeflare.app/hl/public"],
  "conflux": ["https://lb.routeme.sh/rpc/evm/1030", "https://conflux-espace-public.unifra.io", "https://conflux-espace.blockpi.network/v1/rpc/public"],
  "metis": ["https://lb.routeme.sh/rpc/evm/1088", "https://metis-public.nodies.app", "https://metis.drpc.org", "https://metis-andromeda.rpc.thirdweb.com/"],
  "polygonzkevm": ["https://lb.routeme.sh/rpc/evm/1101", "https://rpc.polygon-zkevm.gateway.fm", "https://public.1rpc.io/polygon/zkevm", "https://polygon-zkevm-mainnet.public.blastapi.io"],
  "coredao": ["https://lb.routeme.sh/rpc/evm/1116", "https://public.1rpc.io/core", "https://rpc.ankr.com/core", "https://core.drpc.org"],
  "lisk": ["https://lb.routeme.sh/rpc/evm/1135", "https://lisk.drpc.org", "https://lisk.gateway.tenderly.co", "https://api-lisk-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  "moonbeam": ["https://lb.routeme.sh/rpc/evm/1284", "https://moonbeam.api.onfinality.io/public", "https://moonbeam.unitedbloc.com", "https://public.1rpc.io/glmr"],
  "moonriver": ["https://lb.routeme.sh/rpc/evm/1285", "https://moonriver.api.onfinality.io/public", "https://moonriver.unitedbloc.com", "https://moonriver-rpc.dwellir.com"],
  "sei": ["https://lb.routeme.sh/rpc/evm/1329", "https://evm-rpc.sei-apis.com", "https://sei.drpc.org", "https://sei-evm-rpc.stakeme.pro"],
  "vana": ["https://rpc.vana.org", "https://evm-rpc-vana.josephtran.xyz", "https://evm-rpc-vana.j-node.net", "https://islander-vana-rpc.spidernode.net"],
  "story": ["https://lb.routeme.sh/rpc/evm/1514", "https://mainnet.storyrpc.io", "https://story-evm-rpc.spidernode.net", "https://evm-rpc.story.mainnet.dteam.tech"],
  "tenet": ["https://lb.routeme.sh/rpc/evm/1559", "https://rpc.ankr.com/tenet_evm"],
  "gravity": ["https://lb.routeme.sh/rpc/evm/1625", "https://rpc.ankr.com/gravity"],
  "metal": ["https://lb.routeme.sh/rpc/evm/1750", "https://metall2.drpc.org"],
  "soneium": ["https://lb.routeme.sh/rpc/evm/1868", "https://rpc.nodeflare.app/soneium/public", "https://soneium.drpc.org", "https://soneium-mainnet.rpc.sentio.xyz"],
  "lightlinkphoenixmainnet": ["https://lb.routeme.sh/rpc/evm/1890", "https://endpoints.omniatech.io/v1/lightlink/phoenix/public"],
  "swell": ["https://lb.routeme.sh/rpc/evm/1923", "https://swell-mainnet.rpc.sentio.xyz"],
  "dogechain": ["https://lb.routeme.sh/rpc/evm/2000", "https://rpc-us.dogechain.dog", "https://rpc-sg.dogechain.dog", "https://rpc01-sg.dogechain.dog"],
  "ronin": ["https://lb.routeme.sh/rpc/evm/2020", "https://ronin.drpc.org", "https://ronin-mainnet.gateway.tatum.io/", "https://api-ronin-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  "snaxchain": ["https://snaxchain.drpc.org"],
  "kava": ["https://lb.routeme.sh/rpc/evm/2222", "https://kava.api.onfinality.io/public", "https://kava-evm-rpc.publicnode.com", "https://kava-public.nodies.app"],
  "inevm": ["https://lb.routeme.sh/rpc/evm/2525"],
  "abstract": ["https://lb.routeme.sh/rpc/evm/2741", "https://abstract.drpc.org", "https://abstract.api.onfinality.io/public", "https://abstract-mainnet.gateway.tatum.io/"],
  "morph": ["https://lb.routeme.sh/rpc/evm/2818", "https://rpc-quicknode.morphl2.io", "https://morph.drpc.org"],
  "peaq": ["https://lb.routeme.sh/rpc/evm/3338"],
  "botanix": ["https://rpc.ankr.com/botanix_mainnet"],
  "merlin": ["https://lb.routeme.sh/rpc/evm/4200", "https://merlin.blockpi.network/v1/rpc/public", "https://rpc-merlin.rockx.com", "https://merlin-mainnet-enterprise.unifra.io"],
  "tempo": ["https://lb.routeme.sh/rpc/evm/4217"],
  "megaeth": ["https://lb.routeme.sh/rpc/evm/4326", "https://rpc-megaeth-mainnet.globalstake.io/", "https://megaeth.drpc.org", "https://megaeth.rpc.sentio.xyz"],
  "robinhood": ["https://robinhood.rpc.blxrbdn.com", "https://robinhood-rpc.publicnode.com", "https://robinhood.api.pocket.network", "https://lb.routeme.sh/rpc/evm/4663"],
  "mantle": ["https://lb.routeme.sh/rpc/evm/5000", "https://rpc.nodeflare.app/mantle/public", "https://mantle-mainnet.public.blastapi.io", "https://mantle-public.nodies.app"],
  "somnia": ["https://somnia-rpc.publicnode.com"],
  "superseed": ["https://lb.routeme.sh/rpc/evm/5330", "https://superseed.drpc.org"],
  "zetachain": ["https://lb.routeme.sh/rpc/evm/7000", "https://zetachain-mainnet.g.allthatnode.com/archive/evm", "https://zeta-chain.drpc.org", "https://zetachain-mainnet.public.blastapi.io"],
  "cyber": ["https://lb.routeme.sh/rpc/evm/7560"],
  "canto": ["https://lb.routeme.sh/rpc/evm/7700", "https://canto.gravitychain.io/", "https://canto.evm.chandrastation.com/", "https://jsonrpc.canto.nodestake.top/"],
  "kinto": ["https://rpc.ankr.com/kinto"],
  "deprecatedpolynomial": ["https://lb.routeme.sh/rpc/evm/8008"],
  "kaia": ["https://lb.routeme.sh/rpc/evm/8217", "https://alpha-hardworking-orb.kaia-mainnet.quiknode.pro/", "https://kaia.api.pocket.network", "https://kaia-public.nodies.app"],
  "b3": ["https://lb.routeme.sh/rpc/evm/8333"],
  "base": ["https://lb.routeme.sh/rpc/evm/8453", "https://rpc.nodeflare.app/base/public", "https://developer-access-mainnet.base.org", "https://li-fi-base.intustechno.workers.dev/rpc"],
  "evmos": ["https://lb.routeme.sh/rpc/evm/9001", "https://evmos.lava.build", "https://evmos-mainnet.public.blastapi.io", "https://evmos-evm-rpc.publicnode.com"],
  "plasma": ["https://lb.routeme.sh/rpc/evm/9745", "https://rpc.nodeflare.app/plasma/public", "https://plasma.drpc.org", "https://plasma.api.onfinality.io/public"],
  "deprecatedimmutablezkevm": ["https://lb.routeme.sh/rpc/evm/13371", "https://immutable-zkevm.drpc.org", "https://immutable.gateway.tenderly.co"],
  "apechain": ["https://lb.routeme.sh/rpc/evm/33139", "https://rpc.apechain.com", "https://apechain.drpc.org"],
  "funki": ["https://lb.routeme.sh/rpc/evm/33979"],
  "mode": ["https://lb.routeme.sh/rpc/evm/34443", "https://rpc.nodeflare.app/mode/public", "https://public.1rpc.io/mode", "https://mode.drpc.org"],
  "adichain": ["https://adi.drpc.org"],
  "alephzeroevmmainnet": ["https://lb.routeme.sh/rpc/evm/41455", "https://alephzero.drpc.org"],
  "arbitrum": ["https://lb.routeme.sh/rpc/evm/42161", "https://rpc.nodeflare.app/arb/public", "https://public.1rpc.io/arb", "https://rpc.ankr.com/arbitrum/c4cc6a8c87ec30258076de433ab2cf3d834228aae3fc4d76087873e4fea11635"],
  "arbitrumnova": ["https://lb.routeme.sh/rpc/evm/42170", "https://rpc.nodeflare.app/nova/public", "https://arbitrum-nova.public.blastapi.io", "https://arbitrum-nova-rpc.publicnode.com"],
  "celo": ["https://lb.routeme.sh/rpc/evm/42220", "https://rpc.celocolombia.org", "https://rpc.ankr.com/celo", "https://celo-mainnet.gateway.tatum.io"],
  "hemi": ["https://lb.routeme.sh/rpc/evm/43111", "https://hemi.drpc.org"],
  "avalanche": ["https://lb.routeme.sh/rpc/evm/43114", "https://rpc.nodeflare.app/avax/public", "https://avalanche.public-rpc.com", "https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc"],
  "zircuit": ["https://lb.routeme.sh/rpc/evm/48900", "https://rpc.nodeflare.app/zircuit/public", "https://zircuit1-mainnet.liquify.com", "https://zircuit.rpc.sentio.xyz"],
  "sophon": ["https://lb.routeme.sh/rpc/evm/50104", "https://rpc-quicknode.sophon.xyz"],
  "electroneum": ["https://lb.routeme.sh/rpc/evm/52014", "https://rpc.ankr.com/electroneum"],
  "deprecatedsuperposition": ["https://lb.routeme.sh/rpc/evm/55244"],
  "ink": ["https://lb.routeme.sh/rpc/evm/57073", "https://rpc.nodeflare.app/ink/public", "https://ink.drpc.org", "https://ink-public.nodies.app"],
  "linea": ["https://lb.routeme.sh/rpc/evm/59144", "https://rpc.nodeflare.app/linea/public", "https://public.1rpc.io/linea", "https://linea.drpc.org"],
  "bob": ["https://lb.routeme.sh/rpc/evm/60808", "https://rpc.nodeflare.app/bob/public", "https://bob.drpc.org", "https://bob.gateway.tenderly.co"],
  "berachain": ["https://lb.routeme.sh/rpc/evm/80094", "https://berachain-rpc.publicnode.com", "https://berachain.drpc.org", "https://rpc.berachain-apis.com"],
  "blast": ["https://lb.routeme.sh/rpc/evm/81457", "https://blast.din.dev/rpc", "https://blastl2-mainnet.public.blastapi.io", "https://li-fi-blast.intustechno.workers.dev/rpc"],
  "chilizmainnet": ["https://lb.routeme.sh/rpc/evm/88888", "https://rpc.ankr.com/chiliz", "https://chiliz-mainnet.gateway.tatum.io/", "https://api-chiliz-mainnet-archive.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  "plume": ["https://lb.routeme.sh/rpc/evm/98866", "https://plume.drpc.org", "https://plume-mainnet.gateway.tatum.io/"],
  "real": ["https://lb.routeme.sh/rpc/evm/111188", "https://tangible-real.gateway.tenderly.co", "https://real.drpc.org"],
  "taiko": ["https://lb.routeme.sh/rpc/evm/167000", "https://rpc.taiko.xyz", "https://rpc.ankr.com/taiko", "https://rpc.taiko.tools"],
  "bitlayer": ["https://lb.routeme.sh/rpc/evm/200901", "https://rpc.ankr.com/bitlayer"],
  "scroll": ["https://lb.routeme.sh/rpc/evm/534352", "https://rpc-scroll.icecreamswap.com", "https://scroll-mainnet.public.blastapi.io/", "https://scroll-mainnet-public.unifra.io"],
  "zeronetwork": ["https://lb.routeme.sh/rpc/evm/543210", "https://zero.drpc.org"],
  "xai": ["https://lb.routeme.sh/rpc/evm/660279", "https://rpc.ankr.com/xai"],
  "katana": ["https://lb.routeme.sh/rpc/evm/747474", "https://katana.drpc.org", "https://rpc.swiftnodes.io/rpc/katana", "https://katana.rpc.sentio.xyz"],
  "zklink": ["https://lb.routeme.sh/rpc/evm/810180"],
  "forma": ["https://lb.routeme.sh/rpc/evm/984122"],
  "xrplevm": ["https://xrplevm.buildintheshade.com", "https://xrpl.drpc.org"],
  "zoramainnet": ["https://lb.routeme.sh/rpc/evm/7777777", "https://zora.drpc.org", "https://api-zora-mainnet.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c"],
  "corn": ["https://lb.routeme.sh/rpc/evm/21000000", "https://mainnet.corn-rpc.com", "https://rpc.ankr.com/corn_maizenet", "https://maizenet-rpc.usecorn.com"],
  "degenchain": ["https://lb.routeme.sh/rpc/evm/666666666"],
  "tron": ["https://lb.routeme.sh/rpc/evm/728126428", "https://tron.drpc.org", "https://tron.therpc.io/jsonrpc", "https://tron.api.pocket.network"],
  "ancient8": ["https://lb.routeme.sh/rpc/evm/888888888"],
  "lumia": ["https://lb.routeme.sh/rpc/evm/994873017"],
  "aurora": ["https://lb.routeme.sh/rpc/evm/1313161554", "https://public.1rpc.io/aurora", "https://aurora.drpc.org", "https://aurora-mainnet.gateway.tatum.io"],
  "harmony": ["https://lb.routeme.sh/rpc/evm/1666600000", "https://api.harmony.one", "https://a.api.s0.t.hmny.io", "https://api.s0.t.hmny.io"],
};
